FROM dunglas/frankenphp:1.11-builder-php8.5 AS builder

RUN apt-get update && apt-get install -y protobuf-compiler golang-go

COPY --from=caddy:builder /usr/bin/xcaddy /usr/bin/xcaddy

RUN CGO_ENABLED=1 \
    XCADDY_SETCAP=1 \
    XCADDY_GO_BUILD_FLAGS="-ldflags='-w -s' -tags=nobadger,nomysql,nopgx" \
    CGO_CFLAGS=$(php-config --includes) \
    CGO_LDFLAGS="$(php-config --ldflags) $(php-config --libs)" \
    xcaddy build \
        --output /usr/local/bin/frankenphp \
        --with github.com/dunglas/frankenphp=./ \
        --with github.com/dunglas/frankenphp/caddy=./caddy/ \
        --with github.com/dunglas/caddy-cbrotli \
        --with github.com/dunglas/mercure/caddy \
        --with github.com/baldinof/caddy-supervisor

FROM dunglas/frankenphp:1.11-php8.5 AS php_builder

WORKDIR /app

COPY --from=composer /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./

RUN install-php-extensions zip

RUN composer install --no-dev --no-scripts --no-autoloader

FROM node:22-alpine AS assets

WORKDIR /app

COPY --from=php_builder /app/vendor ./vendor

COPY . .

RUN npm install
RUN npm run build

FROM dunglas/frankenphp:1.11-php8.5 AS runner

WORKDIR /app

COPY --from=builder /usr/local/bin/frankenphp /usr/local/bin/frankenphp
COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY --from=assets /app/public/build ./public/build
COPY --from=php_builder /app/vendor ./vendor

COPY . .

ARG USER=appuser

RUN apt-get update && apt-get install -y protobuf-compiler

RUN install-php-extensions \
	apcu \
	brotli \
	gd \
	intl \
	pdo_sqlite \
	protobuf \
	opcache \
    zip

RUN groupadd -g 1000 ${USER} && \
    useradd -u 1000 -g ${USER} -m -s /bin/bash ${USER}

RUN \
    setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/frankenphp; \
    chown -R ${USER}:${USER} /config/caddy /data/caddy

RUN cp Caddyfile.prod /etc/frankenphp/Caddyfile

RUN echo "APP_ENV=prod" >> .env.local
RUN echo "APP_DEBUG=0" >> .env.local
RUN echo "APP_SECRET=$(head -c 32 /dev/urandom | base64)" >> .env.local

RUN composer dump-autoload --optimize --classmap-authoritative --no-dev && \
    php bin/console cache:clear && \
    php bin/console cache:warmup

RUN php bin/console doctrine:migrations:migrate

RUN chown -R ${USER}:${USER} /app

USER ${USER}

