<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus\FeaturedTitlesView;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.FeaturedTitlesView.Contents</code>
 */
class Contents extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .MangaPlus.Banner banner = 1;</code>
     */
    protected $banner = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.TitleList titleList = 2;</code>
     */
    protected $titleList = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Banner $banner
     *     @type \App\Api\Protobuf\MangaPlus\TitleList $titleList
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Banner banner = 1;</code>
     * @return \App\Api\Protobuf\MangaPlus\Banner|null
     */
    public function getBanner()
    {
        return $this->banner;
    }

    public function hasBanner()
    {
        return isset($this->banner);
    }

    public function clearBanner()
    {
        unset($this->banner);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Banner banner = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\Banner $var
     * @return $this
     */
    public function setBanner($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Banner::class);
        $this->banner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.TitleList titleList = 2;</code>
     * @return \App\Api\Protobuf\MangaPlus\TitleList|null
     */
    public function getTitleList()
    {
        return $this->titleList;
    }

    public function hasTitleList()
    {
        return isset($this->titleList);
    }

    public function clearTitleList()
    {
        unset($this->titleList);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.TitleList titleList = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\TitleList $var
     * @return $this
     */
    public function setTitleList($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\TitleList::class);
        $this->titleList = $var;

        return $this;
    }

}

