<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus\Popup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Popup.AppDefault</code>
 */
class AppDefault extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string subject = 1;</code>
     */
    protected $subject = null;
    /**
     * Generated from protobuf field <code>optional string body = 2;</code>
     */
    protected $body = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.TransitionAction action = 3;</code>
     */
    protected $action = null;
    /**
     * Generated from protobuf field <code>optional string imageUrl = 4;</code>
     */
    protected $imageUrl = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $subject
     *     @type string $body
     *     @type \App\Api\Protobuf\MangaPlus\TransitionAction $action
     *     @type string $imageUrl
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string subject = 1;</code>
     * @return string
     */
    public function getSubject()
    {
        return isset($this->subject) ? $this->subject : '';
    }

    public function hasSubject()
    {
        return isset($this->subject);
    }

    public function clearSubject()
    {
        unset($this->subject);
    }

    /**
     * Generated from protobuf field <code>optional string subject = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string body = 2;</code>
     * @return string
     */
    public function getBody()
    {
        return isset($this->body) ? $this->body : '';
    }

    public function hasBody()
    {
        return isset($this->body);
    }

    public function clearBody()
    {
        unset($this->body);
    }

    /**
     * Generated from protobuf field <code>optional string body = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.TransitionAction action = 3;</code>
     * @return \App\Api\Protobuf\MangaPlus\TransitionAction|null
     */
    public function getAction()
    {
        return $this->action;
    }

    public function hasAction()
    {
        return isset($this->action);
    }

    public function clearAction()
    {
        unset($this->action);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.TransitionAction action = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\TransitionAction $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\TransitionAction::class);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string imageUrl = 4;</code>
     * @return string
     */
    public function getImageUrl()
    {
        return isset($this->imageUrl) ? $this->imageUrl : '';
    }

    public function hasImageUrl()
    {
        return isset($this->imageUrl);
    }

    public function clearImageUrl()
    {
        unset($this->imageUrl);
    }

    /**
     * Generated from protobuf field <code>optional string imageUrl = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->imageUrl = $var;

        return $this;
    }

}

