<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus\Popup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Popup.OSDefault</code>
 */
class OSDefault extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string subject = 1;</code>
     */
    protected $subject = '';
    /**
     * Generated from protobuf field <code>string body = 2;</code>
     */
    protected $body = '';
    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.Button okButton = 3;</code>
     */
    protected $okButton = null;
    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.Button neutralButton = 4;</code>
     */
    protected $neutralButton = null;
    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.Button cancelButton = 5;</code>
     */
    protected $cancelButton = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $subject
     *     @type string $body
     *     @type \App\Api\Protobuf\MangaPlus\Popup\Button $okButton
     *     @type \App\Api\Protobuf\MangaPlus\Popup\Button $neutralButton
     *     @type \App\Api\Protobuf\MangaPlus\Popup\Button $cancelButton
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string subject = 1;</code>
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Generated from protobuf field <code>string subject = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string body = 2;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>string body = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.Button okButton = 3;</code>
     * @return \App\Api\Protobuf\MangaPlus\Popup\Button|null
     */
    public function getOkButton()
    {
        return $this->okButton;
    }

    public function hasOkButton()
    {
        return isset($this->okButton);
    }

    public function clearOkButton()
    {
        unset($this->okButton);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.Button okButton = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\Popup\Button $var
     * @return $this
     */
    public function setOkButton($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Popup\Button::class);
        $this->okButton = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.Button neutralButton = 4;</code>
     * @return \App\Api\Protobuf\MangaPlus\Popup\Button|null
     */
    public function getNeutralButton()
    {
        return $this->neutralButton;
    }

    public function hasNeutralButton()
    {
        return isset($this->neutralButton);
    }

    public function clearNeutralButton()
    {
        unset($this->neutralButton);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.Button neutralButton = 4;</code>
     * @param \App\Api\Protobuf\MangaPlus\Popup\Button $var
     * @return $this
     */
    public function setNeutralButton($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Popup\Button::class);
        $this->neutralButton = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.Button cancelButton = 5;</code>
     * @return \App\Api\Protobuf\MangaPlus\Popup\Button|null
     */
    public function getCancelButton()
    {
        return $this->cancelButton;
    }

    public function hasCancelButton()
    {
        return isset($this->cancelButton);
    }

    public function clearCancelButton()
    {
        unset($this->cancelButton);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.Button cancelButton = 5;</code>
     * @param \App\Api\Protobuf\MangaPlus\Popup\Button $var
     * @return $this
     */
    public function setCancelButton($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Popup\Button::class);
        $this->cancelButton = $var;

        return $this;
    }

}

