<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus\Page;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Page.BannerList</code>
 */
class BannerList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string bannerTitle = 1;</code>
     */
    protected $bannerTitle = null;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner banners = 2;</code>
     */
    private $banners;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bannerTitle
     *     @type \App\Api\Protobuf\MangaPlus\Banner[] $banners
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string bannerTitle = 1;</code>
     * @return string
     */
    public function getBannerTitle()
    {
        return isset($this->bannerTitle) ? $this->bannerTitle : '';
    }

    public function hasBannerTitle()
    {
        return isset($this->bannerTitle);
    }

    public function clearBannerTitle()
    {
        unset($this->bannerTitle);
    }

    /**
     * Generated from protobuf field <code>optional string bannerTitle = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBannerTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->bannerTitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner banners = 2;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Banner>
     */
    public function getBanners()
    {
        return $this->banners;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner banners = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\Banner[] $var
     * @return $this
     */
    public function setBanners($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Banner::class);
        $this->banners = $arr;

        return $this;
    }

}

