<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus\Page;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Page.LastPage</code>
 */
class LastPage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .MangaPlus.Chapter currentChapter = 1;</code>
     */
    protected $currentChapter = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.Chapter nextChapter = 2;</code>
     */
    protected $nextChapter = null;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Comment topComments = 3;</code>
     */
    private $topComments;
    /**
     * Generated from protobuf field <code>optional bool isSubscribed = 4;</code>
     */
    protected $isSubscribed = null;
    /**
     * Generated from protobuf field <code>optional uint32 nextTimeStamp = 5;</code>
     */
    protected $nextTimeStamp = null;
    /**
     * Generated from protobuf field <code>optional int32 chapterType = 6;</code>
     */
    protected $chapterType = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetworkList advertisement = 7;</code>
     */
    protected $advertisement = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.Popup movieReward = 8;</code>
     */
    protected $movieReward = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Chapter $currentChapter
     *     @type \App\Api\Protobuf\MangaPlus\Chapter $nextChapter
     *     @type \App\Api\Protobuf\MangaPlus\Comment[] $topComments
     *     @type bool $isSubscribed
     *     @type int $nextTimeStamp
     *     @type int $chapterType
     *     @type \App\Api\Protobuf\MangaPlus\AdNetworkList $advertisement
     *     @type \App\Api\Protobuf\MangaPlus\Popup $movieReward
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Chapter currentChapter = 1;</code>
     * @return \App\Api\Protobuf\MangaPlus\Chapter|null
     */
    public function getCurrentChapter()
    {
        return $this->currentChapter;
    }

    public function hasCurrentChapter()
    {
        return isset($this->currentChapter);
    }

    public function clearCurrentChapter()
    {
        unset($this->currentChapter);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Chapter currentChapter = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\Chapter $var
     * @return $this
     */
    public function setCurrentChapter($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Chapter::class);
        $this->currentChapter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Chapter nextChapter = 2;</code>
     * @return \App\Api\Protobuf\MangaPlus\Chapter|null
     */
    public function getNextChapter()
    {
        return $this->nextChapter;
    }

    public function hasNextChapter()
    {
        return isset($this->nextChapter);
    }

    public function clearNextChapter()
    {
        unset($this->nextChapter);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Chapter nextChapter = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\Chapter $var
     * @return $this
     */
    public function setNextChapter($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Chapter::class);
        $this->nextChapter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Comment topComments = 3;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Comment>
     */
    public function getTopComments()
    {
        return $this->topComments;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Comment topComments = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\Comment[] $var
     * @return $this
     */
    public function setTopComments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Comment::class);
        $this->topComments = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool isSubscribed = 4;</code>
     * @return bool
     */
    public function getIsSubscribed()
    {
        return isset($this->isSubscribed) ? $this->isSubscribed : false;
    }

    public function hasIsSubscribed()
    {
        return isset($this->isSubscribed);
    }

    public function clearIsSubscribed()
    {
        unset($this->isSubscribed);
    }

    /**
     * Generated from protobuf field <code>optional bool isSubscribed = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSubscribed($var)
    {
        GPBUtil::checkBool($var);
        $this->isSubscribed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 nextTimeStamp = 5;</code>
     * @return int
     */
    public function getNextTimeStamp()
    {
        return isset($this->nextTimeStamp) ? $this->nextTimeStamp : 0;
    }

    public function hasNextTimeStamp()
    {
        return isset($this->nextTimeStamp);
    }

    public function clearNextTimeStamp()
    {
        unset($this->nextTimeStamp);
    }

    /**
     * Generated from protobuf field <code>optional uint32 nextTimeStamp = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setNextTimeStamp($var)
    {
        GPBUtil::checkUint32($var);
        $this->nextTimeStamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 chapterType = 6;</code>
     * @return int
     */
    public function getChapterType()
    {
        return isset($this->chapterType) ? $this->chapterType : 0;
    }

    public function hasChapterType()
    {
        return isset($this->chapterType);
    }

    public function clearChapterType()
    {
        unset($this->chapterType);
    }

    /**
     * Generated from protobuf field <code>optional int32 chapterType = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setChapterType($var)
    {
        GPBUtil::checkInt32($var);
        $this->chapterType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetworkList advertisement = 7;</code>
     * @return \App\Api\Protobuf\MangaPlus\AdNetworkList|null
     */
    public function getAdvertisement()
    {
        return $this->advertisement;
    }

    public function hasAdvertisement()
    {
        return isset($this->advertisement);
    }

    public function clearAdvertisement()
    {
        unset($this->advertisement);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetworkList advertisement = 7;</code>
     * @param \App\Api\Protobuf\MangaPlus\AdNetworkList $var
     * @return $this
     */
    public function setAdvertisement($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\AdNetworkList::class);
        $this->advertisement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Popup movieReward = 8;</code>
     * @return \App\Api\Protobuf\MangaPlus\Popup|null
     */
    public function getMovieReward()
    {
        return $this->movieReward;
    }

    public function hasMovieReward()
    {
        return isset($this->movieReward);
    }

    public function clearMovieReward()
    {
        unset($this->movieReward);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Popup movieReward = 8;</code>
     * @param \App\Api\Protobuf\MangaPlus\Popup $var
     * @return $this
     */
    public function setMovieReward($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Popup::class);
        $this->movieReward = $var;

        return $this;
    }

}

