<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus\Page;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Page.MangaPage</code>
 */
class MangaPage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string imageUrl = 1;</code>
     */
    protected $imageUrl = null;
    /**
     * Generated from protobuf field <code>optional uint32 width = 2;</code>
     */
    protected $width = null;
    /**
     * Generated from protobuf field <code>optional uint32 height = 3;</code>
     */
    protected $height = null;
    /**
     * Generated from protobuf field <code>optional int32 type = 4;</code>
     */
    protected $type = null;
    /**
     * Generated from protobuf field <code>optional string encryptionKey = 5;</code>
     */
    protected $encryptionKey = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $imageUrl
     *     @type int $width
     *     @type int $height
     *     @type int $type
     *     @type string $encryptionKey
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string imageUrl = 1;</code>
     * @return string
     */
    public function getImageUrl()
    {
        return isset($this->imageUrl) ? $this->imageUrl : '';
    }

    public function hasImageUrl()
    {
        return isset($this->imageUrl);
    }

    public function clearImageUrl()
    {
        unset($this->imageUrl);
    }

    /**
     * Generated from protobuf field <code>optional string imageUrl = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->imageUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 width = 2;</code>
     * @return int
     */
    public function getWidth()
    {
        return isset($this->width) ? $this->width : 0;
    }

    public function hasWidth()
    {
        return isset($this->width);
    }

    public function clearWidth()
    {
        unset($this->width);
    }

    /**
     * Generated from protobuf field <code>optional uint32 width = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkUint32($var);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 height = 3;</code>
     * @return int
     */
    public function getHeight()
    {
        return isset($this->height) ? $this->height : 0;
    }

    public function hasHeight()
    {
        return isset($this->height);
    }

    public function clearHeight()
    {
        unset($this->height);
    }

    /**
     * Generated from protobuf field <code>optional uint32 height = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkUint32($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 type = 4;</code>
     * @return int
     */
    public function getType()
    {
        return isset($this->type) ? $this->type : 0;
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * Generated from protobuf field <code>optional int32 type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string encryptionKey = 5;</code>
     * @return string
     */
    public function getEncryptionKey()
    {
        return isset($this->encryptionKey) ? $this->encryptionKey : '';
    }

    public function hasEncryptionKey()
    {
        return isset($this->encryptionKey);
    }

    public function clearEncryptionKey()
    {
        unset($this->encryptionKey);
    }

    /**
     * Generated from protobuf field <code>optional string encryptionKey = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEncryptionKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->encryptionKey = $var;

        return $this;
    }

}

