<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus\AdNetwork;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.AdNetwork.Facebook</code>
 */
class Facebook extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string placementID = 1;</code>
     */
    protected $placementID = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $placementID
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string placementID = 1;</code>
     * @return string
     */
    public function getPlacementID()
    {
        return isset($this->placementID) ? $this->placementID : '';
    }

    public function hasPlacementID()
    {
        return isset($this->placementID);
    }

    public function clearPlacementID()
    {
        unset($this->placementID);
    }

    /**
     * Generated from protobuf field <code>optional string placementID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlacementID($var)
    {
        GPBUtil::checkString($var, True);
        $this->placementID = $var;

        return $this;
    }

}

