<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus\AdNetwork;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.AdNetwork.Mopub</code>
 */
class Mopub extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string unitID = 1;</code>
     */
    protected $unitID = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $unitID
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string unitID = 1;</code>
     * @return string
     */
    public function getUnitID()
    {
        return isset($this->unitID) ? $this->unitID : '';
    }

    public function hasUnitID()
    {
        return isset($this->unitID);
    }

    public function clearUnitID()
    {
        unset($this->unitID);
    }

    /**
     * Generated from protobuf field <code>optional string unitID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUnitID($var)
    {
        GPBUtil::checkString($var, True);
        $this->unitID = $var;

        return $this;
    }

}

