<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.AdNetwork</code>
 */
class AdNetwork extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Facebook facebook = 1;</code>
     */
    protected $facebook = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Admob admob = 2;</code>
     */
    protected $admob = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Mopub mopub = 3;</code>
     */
    protected $mopub = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Adsense adsense = 4;</code>
     */
    protected $adsense = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Applovin applovin = 5;</code>
     */
    protected $applovin = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\AdNetwork\Facebook $facebook
     *     @type \App\Api\Protobuf\MangaPlus\AdNetwork\Admob $admob
     *     @type \App\Api\Protobuf\MangaPlus\AdNetwork\Mopub $mopub
     *     @type \App\Api\Protobuf\MangaPlus\AdNetwork\Adsense $adsense
     *     @type \App\Api\Protobuf\MangaPlus\AdNetwork\Applovin $applovin
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Facebook facebook = 1;</code>
     * @return \App\Api\Protobuf\MangaPlus\AdNetwork\Facebook|null
     */
    public function getFacebook()
    {
        return $this->facebook;
    }

    public function hasFacebook()
    {
        return isset($this->facebook);
    }

    public function clearFacebook()
    {
        unset($this->facebook);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Facebook facebook = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\AdNetwork\Facebook $var
     * @return $this
     */
    public function setFacebook($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\AdNetwork\Facebook::class);
        $this->facebook = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Admob admob = 2;</code>
     * @return \App\Api\Protobuf\MangaPlus\AdNetwork\Admob|null
     */
    public function getAdmob()
    {
        return $this->admob;
    }

    public function hasAdmob()
    {
        return isset($this->admob);
    }

    public function clearAdmob()
    {
        unset($this->admob);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Admob admob = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\AdNetwork\Admob $var
     * @return $this
     */
    public function setAdmob($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\AdNetwork\Admob::class);
        $this->admob = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Mopub mopub = 3;</code>
     * @return \App\Api\Protobuf\MangaPlus\AdNetwork\Mopub|null
     */
    public function getMopub()
    {
        return $this->mopub;
    }

    public function hasMopub()
    {
        return isset($this->mopub);
    }

    public function clearMopub()
    {
        unset($this->mopub);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Mopub mopub = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\AdNetwork\Mopub $var
     * @return $this
     */
    public function setMopub($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\AdNetwork\Mopub::class);
        $this->mopub = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Adsense adsense = 4;</code>
     * @return \App\Api\Protobuf\MangaPlus\AdNetwork\Adsense|null
     */
    public function getAdsense()
    {
        return $this->adsense;
    }

    public function hasAdsense()
    {
        return isset($this->adsense);
    }

    public function clearAdsense()
    {
        unset($this->adsense);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Adsense adsense = 4;</code>
     * @param \App\Api\Protobuf\MangaPlus\AdNetwork\Adsense $var
     * @return $this
     */
    public function setAdsense($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\AdNetwork\Adsense::class);
        $this->adsense = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Applovin applovin = 5;</code>
     * @return \App\Api\Protobuf\MangaPlus\AdNetwork\Applovin|null
     */
    public function getApplovin()
    {
        return $this->applovin;
    }

    public function hasApplovin()
    {
        return isset($this->applovin);
    }

    public function clearApplovin()
    {
        unset($this->applovin);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetwork.Applovin applovin = 5;</code>
     * @param \App\Api\Protobuf\MangaPlus\AdNetwork\Applovin $var
     * @return $this
     */
    public function setApplovin($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\AdNetwork\Applovin::class);
        $this->applovin = $var;

        return $this;
    }

}

