<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.AdNetworkList</code>
 */
class AdNetworkList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.AdNetwork adNetworks = 1;</code>
     */
    private $adNetworks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\AdNetwork[] $adNetworks
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.AdNetwork adNetworks = 1;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\AdNetwork>
     */
    public function getAdNetworks()
    {
        return $this->adNetworks;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.AdNetwork adNetworks = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\AdNetwork[] $var
     * @return $this
     */
    public function setAdNetworks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\AdNetwork::class);
        $this->adNetworks = $arr;

        return $this;
    }

}

