<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.AllTitlesGroup</code>
 */
class AllTitlesGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string theTitle = 1;</code>
     */
    protected $theTitle = '';
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title titles = 2;</code>
     */
    private $titles;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Tag tags = 3;</code>
     */
    private $tags;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Label labels = 4;</code>
     */
    private $labels;
    /**
     * Generated from protobuf field <code>uint32 nextChapterStartTimestamp = 5;</code>
     */
    protected $nextChapterStartTimestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $theTitle
     *     @type \App\Api\Protobuf\MangaPlus\Title[] $titles
     *     @type \App\Api\Protobuf\MangaPlus\Tag[] $tags
     *     @type \App\Api\Protobuf\MangaPlus\Label[] $labels
     *     @type int $nextChapterStartTimestamp
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string theTitle = 1;</code>
     * @return string
     */
    public function getTheTitle()
    {
        return $this->theTitle;
    }

    /**
     * Generated from protobuf field <code>string theTitle = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTheTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->theTitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title titles = 2;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Title>
     */
    public function getTitles()
    {
        return $this->titles;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title titles = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\Title[] $var
     * @return $this
     */
    public function setTitles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Title::class);
        $this->titles = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Tag tags = 3;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Tag>
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Tag tags = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\Tag[] $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Tag::class);
        $this->tags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Label labels = 4;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Label>
     */
    public function getLabels()
    {
        return $this->labels;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Label labels = 4;</code>
     * @param \App\Api\Protobuf\MangaPlus\Label[] $var
     * @return $this
     */
    public function setLabels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Label::class);
        $this->labels = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 nextChapterStartTimestamp = 5;</code>
     * @return int
     */
    public function getNextChapterStartTimestamp()
    {
        return $this->nextChapterStartTimestamp;
    }

    /**
     * Generated from protobuf field <code>uint32 nextChapterStartTimestamp = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setNextChapterStartTimestamp($var)
    {
        GPBUtil::checkUint32($var);
        $this->nextChapterStartTimestamp = $var;

        return $this;
    }

}

