<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.AllTitlesViewV2</code>
 */
class AllTitlesViewV2 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.AllTitlesGroup allTitlesGroup = 1;</code>
     */
    private $allTitlesGroup;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\AllTitlesGroup[] $allTitlesGroup
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.AllTitlesGroup allTitlesGroup = 1;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\AllTitlesGroup>
     */
    public function getAllTitlesGroup()
    {
        return $this->allTitlesGroup;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.AllTitlesGroup allTitlesGroup = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\AllTitlesGroup[] $var
     * @return $this
     */
    public function setAllTitlesGroup($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\AllTitlesGroup::class);
        $this->allTitlesGroup = $arr;

        return $this;
    }

}

