<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.AllTitlesViewV3</code>
 */
class AllTitlesViewV3 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Category categories = 2;</code>
     */
    private $categories;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.TitleContainer titles = 3;</code>
     */
    private $titles;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Category[] $categories
     *     @type \App\Api\Protobuf\MangaPlus\TitleContainer[] $titles
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Category categories = 2;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Category>
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Category categories = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\Category[] $var
     * @return $this
     */
    public function setCategories($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Category::class);
        $this->categories = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.TitleContainer titles = 3;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\TitleContainer>
     */
    public function getTitles()
    {
        return $this->titles;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.TitleContainer titles = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\TitleContainer[] $var
     * @return $this
     */
    public function setTitles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\TitleContainer::class);
        $this->titles = $arr;

        return $this;
    }

}

