<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Banner</code>
 */
class Banner extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string imageUrl = 1;</code>
     */
    protected $imageUrl = '';
    /**
     * Generated from protobuf field <code>.MangaPlus.TransitionAction action = 2;</code>
     */
    protected $action = null;
    /**
     * Generated from protobuf field <code>uint32 id = 3;</code>
     */
    protected $id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $imageUrl
     *     @type \App\Api\Protobuf\MangaPlus\TransitionAction $action
     *     @type int $id
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string imageUrl = 1;</code>
     * @return string
     */
    public function getImageUrl()
    {
        return $this->imageUrl;
    }

    /**
     * Generated from protobuf field <code>string imageUrl = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->imageUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.TransitionAction action = 2;</code>
     * @return \App\Api\Protobuf\MangaPlus\TransitionAction|null
     */
    public function getAction()
    {
        return $this->action;
    }

    public function hasAction()
    {
        return isset($this->action);
    }

    public function clearAction()
    {
        unset($this->action);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.TransitionAction action = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\TransitionAction $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\TransitionAction::class);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 3;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

}

