<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.ChapterGroup</code>
 */
class ChapterGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string chapterNumbers = 1;</code>
     */
    protected $chapterNumbers = '';
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter firstChapterList = 2;</code>
     */
    private $firstChapterList;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter midChapterList = 3;</code>
     */
    private $midChapterList;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter lastChapterList = 4;</code>
     */
    private $lastChapterList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $chapterNumbers
     *     @type \App\Api\Protobuf\MangaPlus\Chapter[] $firstChapterList
     *     @type \App\Api\Protobuf\MangaPlus\Chapter[] $midChapterList
     *     @type \App\Api\Protobuf\MangaPlus\Chapter[] $lastChapterList
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string chapterNumbers = 1;</code>
     * @return string
     */
    public function getChapterNumbers()
    {
        return $this->chapterNumbers;
    }

    /**
     * Generated from protobuf field <code>string chapterNumbers = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setChapterNumbers($var)
    {
        GPBUtil::checkString($var, True);
        $this->chapterNumbers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter firstChapterList = 2;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Chapter>
     */
    public function getFirstChapterList()
    {
        return $this->firstChapterList;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter firstChapterList = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\Chapter[] $var
     * @return $this
     */
    public function setFirstChapterList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Chapter::class);
        $this->firstChapterList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter midChapterList = 3;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Chapter>
     */
    public function getMidChapterList()
    {
        return $this->midChapterList;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter midChapterList = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\Chapter[] $var
     * @return $this
     */
    public function setMidChapterList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Chapter::class);
        $this->midChapterList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter lastChapterList = 4;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Chapter>
     */
    public function getLastChapterList()
    {
        return $this->lastChapterList;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter lastChapterList = 4;</code>
     * @param \App\Api\Protobuf\MangaPlus\Chapter[] $var
     * @return $this
     */
    public function setLastChapterList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Chapter::class);
        $this->lastChapterList = $arr;

        return $this;
    }

}

