<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Chapter</code>
 */
class Chapter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional uint32 titleId = 1;</code>
     */
    protected $titleId = null;
    /**
     * Generated from protobuf field <code>optional uint32 chapterId = 2;</code>
     */
    protected $chapterId = null;
    /**
     * Generated from protobuf field <code>optional string name = 3;</code>
     */
    protected $name = null;
    /**
     * Generated from protobuf field <code>optional string subTitle = 4;</code>
     */
    protected $subTitle = null;
    /**
     * Generated from protobuf field <code>optional string thumbnailUrl = 5;</code>
     */
    protected $thumbnailUrl = null;
    /**
     * Generated from protobuf field <code>optional uint32 startTimeStamp = 6;</code>
     */
    protected $startTimeStamp = null;
    /**
     * Generated from protobuf field <code>optional uint32 endTimeStamp = 7;</code>
     */
    protected $endTimeStamp = null;
    /**
     * Generated from protobuf field <code>optional bool alreadyViewed = 8;</code>
     */
    protected $alreadyViewed = null;
    /**
     * Generated from protobuf field <code>optional bool isVerticalOnly = 9;</code>
     */
    protected $isVerticalOnly = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $titleId
     *     @type int $chapterId
     *     @type string $name
     *     @type string $subTitle
     *     @type string $thumbnailUrl
     *     @type int $startTimeStamp
     *     @type int $endTimeStamp
     *     @type bool $alreadyViewed
     *     @type bool $isVerticalOnly
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 titleId = 1;</code>
     * @return int
     */
    public function getTitleId()
    {
        return isset($this->titleId) ? $this->titleId : 0;
    }

    public function hasTitleId()
    {
        return isset($this->titleId);
    }

    public function clearTitleId()
    {
        unset($this->titleId);
    }

    /**
     * Generated from protobuf field <code>optional uint32 titleId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTitleId($var)
    {
        GPBUtil::checkUint32($var);
        $this->titleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 chapterId = 2;</code>
     * @return int
     */
    public function getChapterId()
    {
        return isset($this->chapterId) ? $this->chapterId : 0;
    }

    public function hasChapterId()
    {
        return isset($this->chapterId);
    }

    public function clearChapterId()
    {
        unset($this->chapterId);
    }

    /**
     * Generated from protobuf field <code>optional uint32 chapterId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setChapterId($var)
    {
        GPBUtil::checkUint32($var);
        $this->chapterId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Generated from protobuf field <code>optional string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string subTitle = 4;</code>
     * @return string
     */
    public function getSubTitle()
    {
        return isset($this->subTitle) ? $this->subTitle : '';
    }

    public function hasSubTitle()
    {
        return isset($this->subTitle);
    }

    public function clearSubTitle()
    {
        unset($this->subTitle);
    }

    /**
     * Generated from protobuf field <code>optional string subTitle = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSubTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->subTitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string thumbnailUrl = 5;</code>
     * @return string
     */
    public function getThumbnailUrl()
    {
        return isset($this->thumbnailUrl) ? $this->thumbnailUrl : '';
    }

    public function hasThumbnailUrl()
    {
        return isset($this->thumbnailUrl);
    }

    public function clearThumbnailUrl()
    {
        unset($this->thumbnailUrl);
    }

    /**
     * Generated from protobuf field <code>optional string thumbnailUrl = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setThumbnailUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->thumbnailUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 startTimeStamp = 6;</code>
     * @return int
     */
    public function getStartTimeStamp()
    {
        return isset($this->startTimeStamp) ? $this->startTimeStamp : 0;
    }

    public function hasStartTimeStamp()
    {
        return isset($this->startTimeStamp);
    }

    public function clearStartTimeStamp()
    {
        unset($this->startTimeStamp);
    }

    /**
     * Generated from protobuf field <code>optional uint32 startTimeStamp = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setStartTimeStamp($var)
    {
        GPBUtil::checkUint32($var);
        $this->startTimeStamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 endTimeStamp = 7;</code>
     * @return int
     */
    public function getEndTimeStamp()
    {
        return isset($this->endTimeStamp) ? $this->endTimeStamp : 0;
    }

    public function hasEndTimeStamp()
    {
        return isset($this->endTimeStamp);
    }

    public function clearEndTimeStamp()
    {
        unset($this->endTimeStamp);
    }

    /**
     * Generated from protobuf field <code>optional uint32 endTimeStamp = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setEndTimeStamp($var)
    {
        GPBUtil::checkUint32($var);
        $this->endTimeStamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool alreadyViewed = 8;</code>
     * @return bool
     */
    public function getAlreadyViewed()
    {
        return isset($this->alreadyViewed) ? $this->alreadyViewed : false;
    }

    public function hasAlreadyViewed()
    {
        return isset($this->alreadyViewed);
    }

    public function clearAlreadyViewed()
    {
        unset($this->alreadyViewed);
    }

    /**
     * Generated from protobuf field <code>optional bool alreadyViewed = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setAlreadyViewed($var)
    {
        GPBUtil::checkBool($var);
        $this->alreadyViewed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool isVerticalOnly = 9;</code>
     * @return bool
     */
    public function getIsVerticalOnly()
    {
        return isset($this->isVerticalOnly) ? $this->isVerticalOnly : false;
    }

    public function hasIsVerticalOnly()
    {
        return isset($this->isVerticalOnly);
    }

    public function clearIsVerticalOnly()
    {
        unset($this->isVerticalOnly);
    }

    /**
     * Generated from protobuf field <code>optional bool isVerticalOnly = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsVerticalOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->isVerticalOnly = $var;

        return $this;
    }

}

