<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Chapter</code>
 */
class Chapter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 titleId = 1;</code>
     */
    protected $titleId = 0;
    /**
     * Generated from protobuf field <code>uint32 chapterId = 2;</code>
     */
    protected $chapterId = 0;
    /**
     * Nom dans v1, correspond souvent au titre
     *
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string subTitle = 4;</code>
     */
    protected $subTitle = '';
    /**
     * Generated from protobuf field <code>string thumbnailUrl = 5;</code>
     */
    protected $thumbnailUrl = '';
    /**
     * Generated from protobuf field <code>int64 startTimeStamp = 6;</code>
     */
    protected $startTimeStamp = 0;
    /**
     * Generated from protobuf field <code>int64 endTimeStamp = 7;</code>
     */
    protected $endTimeStamp = 0;
    /**
     * Generated from protobuf field <code>bool alreadyViewed = 8;</code>
     */
    protected $alreadyViewed = false;
    /**
     * Generated from protobuf field <code>bool isVerticalOnly = 9;</code>
     */
    protected $isVerticalOnly = false;
    /**
     * Adapté du v2 (champ 3) pour éviter les conflits
     *
     * Generated from protobuf field <code>string number = 10;</code>
     */
    protected $number = '';
    /**
     * Generated from protobuf field <code>uint32 commentCount = 13;</code>
     */
    protected $commentCount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $titleId
     *     @type int $chapterId
     *     @type string $name
     *           Nom dans v1, correspond souvent au titre
     *     @type string $subTitle
     *     @type string $thumbnailUrl
     *     @type int|string $startTimeStamp
     *     @type int|string $endTimeStamp
     *     @type bool $alreadyViewed
     *     @type bool $isVerticalOnly
     *     @type string $number
     *           Adapté du v2 (champ 3) pour éviter les conflits
     *     @type int $commentCount
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 titleId = 1;</code>
     * @return int
     */
    public function getTitleId()
    {
        return $this->titleId;
    }

    /**
     * Generated from protobuf field <code>uint32 titleId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTitleId($var)
    {
        GPBUtil::checkUint32($var);
        $this->titleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 chapterId = 2;</code>
     * @return int
     */
    public function getChapterId()
    {
        return $this->chapterId;
    }

    /**
     * Generated from protobuf field <code>uint32 chapterId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setChapterId($var)
    {
        GPBUtil::checkUint32($var);
        $this->chapterId = $var;

        return $this;
    }

    /**
     * Nom dans v1, correspond souvent au titre
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Nom dans v1, correspond souvent au titre
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subTitle = 4;</code>
     * @return string
     */
    public function getSubTitle()
    {
        return $this->subTitle;
    }

    /**
     * Generated from protobuf field <code>string subTitle = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSubTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->subTitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string thumbnailUrl = 5;</code>
     * @return string
     */
    public function getThumbnailUrl()
    {
        return $this->thumbnailUrl;
    }

    /**
     * Generated from protobuf field <code>string thumbnailUrl = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setThumbnailUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->thumbnailUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 startTimeStamp = 6;</code>
     * @return int|string
     */
    public function getStartTimeStamp()
    {
        return $this->startTimeStamp;
    }

    /**
     * Generated from protobuf field <code>int64 startTimeStamp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTimeStamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->startTimeStamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 endTimeStamp = 7;</code>
     * @return int|string
     */
    public function getEndTimeStamp()
    {
        return $this->endTimeStamp;
    }

    /**
     * Generated from protobuf field <code>int64 endTimeStamp = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTimeStamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->endTimeStamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool alreadyViewed = 8;</code>
     * @return bool
     */
    public function getAlreadyViewed()
    {
        return $this->alreadyViewed;
    }

    /**
     * Generated from protobuf field <code>bool alreadyViewed = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setAlreadyViewed($var)
    {
        GPBUtil::checkBool($var);
        $this->alreadyViewed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isVerticalOnly = 9;</code>
     * @return bool
     */
    public function getIsVerticalOnly()
    {
        return $this->isVerticalOnly;
    }

    /**
     * Generated from protobuf field <code>bool isVerticalOnly = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsVerticalOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->isVerticalOnly = $var;

        return $this;
    }

    /**
     * Adapté du v2 (champ 3) pour éviter les conflits
     *
     * Generated from protobuf field <code>string number = 10;</code>
     * @return string
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Adapté du v2 (champ 3) pour éviter les conflits
     *
     * Generated from protobuf field <code>string number = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 commentCount = 13;</code>
     * @return int
     */
    public function getCommentCount()
    {
        return $this->commentCount;
    }

    /**
     * Generated from protobuf field <code>uint32 commentCount = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setCommentCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->commentCount = $var;

        return $this;
    }

}

