<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Comment</code>
 */
class Comment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional uint32 id = 1;</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>optional uint32 index = 2;</code>
     */
    protected $index = null;
    /**
     * Generated from protobuf field <code>optional string userName = 3;</code>
     */
    protected $userName = null;
    /**
     * Generated from protobuf field <code>optional string iconUrl = 4;</code>
     */
    protected $iconUrl = null;
    /**
     *optional TYPE NAME = 5;
     *
     * Generated from protobuf field <code>optional bool isMyComment = 6;</code>
     */
    protected $isMyComment = null;
    /**
     * Generated from protobuf field <code>optional bool alreadyLiked = 7;</code>
     */
    protected $alreadyLiked = null;
    /**
     *optional TYPE NAME = 8;
     *
     * Generated from protobuf field <code>optional uint32 numberOfLikes = 9;</code>
     */
    protected $numberOfLikes = null;
    /**
     * Generated from protobuf field <code>optional string body = 10;</code>
     */
    protected $body = null;
    /**
     * Generated from protobuf field <code>optional uint32 created = 11;</code>
     */
    protected $created = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $index
     *     @type string $userName
     *     @type string $iconUrl
     *     @type bool $isMyComment
     *          optional TYPE NAME = 5;
     *     @type bool $alreadyLiked
     *     @type int $numberOfLikes
     *          optional TYPE NAME = 8;
     *     @type string $body
     *     @type int $created
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : 0;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 index = 2;</code>
     * @return int
     */
    public function getIndex()
    {
        return isset($this->index) ? $this->index : 0;
    }

    public function hasIndex()
    {
        return isset($this->index);
    }

    public function clearIndex()
    {
        unset($this->index);
    }

    /**
     * Generated from protobuf field <code>optional uint32 index = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string userName = 3;</code>
     * @return string
     */
    public function getUserName()
    {
        return isset($this->userName) ? $this->userName : '';
    }

    public function hasUserName()
    {
        return isset($this->userName);
    }

    public function clearUserName()
    {
        unset($this->userName);
    }

    /**
     * Generated from protobuf field <code>optional string userName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->userName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string iconUrl = 4;</code>
     * @return string
     */
    public function getIconUrl()
    {
        return isset($this->iconUrl) ? $this->iconUrl : '';
    }

    public function hasIconUrl()
    {
        return isset($this->iconUrl);
    }

    public function clearIconUrl()
    {
        unset($this->iconUrl);
    }

    /**
     * Generated from protobuf field <code>optional string iconUrl = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIconUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->iconUrl = $var;

        return $this;
    }

    /**
     *optional TYPE NAME = 5;
     *
     * Generated from protobuf field <code>optional bool isMyComment = 6;</code>
     * @return bool
     */
    public function getIsMyComment()
    {
        return isset($this->isMyComment) ? $this->isMyComment : false;
    }

    public function hasIsMyComment()
    {
        return isset($this->isMyComment);
    }

    public function clearIsMyComment()
    {
        unset($this->isMyComment);
    }

    /**
     *optional TYPE NAME = 5;
     *
     * Generated from protobuf field <code>optional bool isMyComment = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMyComment($var)
    {
        GPBUtil::checkBool($var);
        $this->isMyComment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool alreadyLiked = 7;</code>
     * @return bool
     */
    public function getAlreadyLiked()
    {
        return isset($this->alreadyLiked) ? $this->alreadyLiked : false;
    }

    public function hasAlreadyLiked()
    {
        return isset($this->alreadyLiked);
    }

    public function clearAlreadyLiked()
    {
        unset($this->alreadyLiked);
    }

    /**
     * Generated from protobuf field <code>optional bool alreadyLiked = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setAlreadyLiked($var)
    {
        GPBUtil::checkBool($var);
        $this->alreadyLiked = $var;

        return $this;
    }

    /**
     *optional TYPE NAME = 8;
     *
     * Generated from protobuf field <code>optional uint32 numberOfLikes = 9;</code>
     * @return int
     */
    public function getNumberOfLikes()
    {
        return isset($this->numberOfLikes) ? $this->numberOfLikes : 0;
    }

    public function hasNumberOfLikes()
    {
        return isset($this->numberOfLikes);
    }

    public function clearNumberOfLikes()
    {
        unset($this->numberOfLikes);
    }

    /**
     *optional TYPE NAME = 8;
     *
     * Generated from protobuf field <code>optional uint32 numberOfLikes = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setNumberOfLikes($var)
    {
        GPBUtil::checkUint32($var);
        $this->numberOfLikes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string body = 10;</code>
     * @return string
     */
    public function getBody()
    {
        return isset($this->body) ? $this->body : '';
    }

    public function hasBody()
    {
        return isset($this->body);
    }

    public function clearBody()
    {
        unset($this->body);
    }

    /**
     * Generated from protobuf field <code>optional string body = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 created = 11;</code>
     * @return int
     */
    public function getCreated()
    {
        return isset($this->created) ? $this->created : 0;
    }

    public function hasCreated()
    {
        return isset($this->created);
    }

    public function clearCreated()
    {
        unset($this->created);
    }

    /**
     * Generated from protobuf field <code>optional uint32 created = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkUint32($var);
        $this->created = $var;

        return $this;
    }

}

