<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Comment</code>
 */
class Comment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>uint32 index = 2;</code>
     */
    protected $index = 0;
    /**
     * Generated from protobuf field <code>string userName = 3;</code>
     */
    protected $userName = '';
    /**
     * Generated from protobuf field <code>string iconUrl = 4;</code>
     */
    protected $iconUrl = '';
    /**
     * Generated from protobuf field <code>bool isMyComment = 6;</code>
     */
    protected $isMyComment = false;
    /**
     * Generated from protobuf field <code>bool alreadyLiked = 7;</code>
     */
    protected $alreadyLiked = false;
    /**
     * Generated from protobuf field <code>uint32 numberOfLikes = 9;</code>
     */
    protected $numberOfLikes = 0;
    /**
     * Generated from protobuf field <code>string body = 10;</code>
     */
    protected $body = '';
    /**
     * Generated from protobuf field <code>uint32 created = 11;</code>
     */
    protected $created = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $index
     *     @type string $userName
     *     @type string $iconUrl
     *     @type bool $isMyComment
     *     @type bool $alreadyLiked
     *     @type int $numberOfLikes
     *     @type string $body
     *     @type int $created
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 index = 2;</code>
     * @return int
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>uint32 index = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userName = 3;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->userName;
    }

    /**
     * Generated from protobuf field <code>string userName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->userName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string iconUrl = 4;</code>
     * @return string
     */
    public function getIconUrl()
    {
        return $this->iconUrl;
    }

    /**
     * Generated from protobuf field <code>string iconUrl = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIconUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->iconUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isMyComment = 6;</code>
     * @return bool
     */
    public function getIsMyComment()
    {
        return $this->isMyComment;
    }

    /**
     * Generated from protobuf field <code>bool isMyComment = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMyComment($var)
    {
        GPBUtil::checkBool($var);
        $this->isMyComment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool alreadyLiked = 7;</code>
     * @return bool
     */
    public function getAlreadyLiked()
    {
        return $this->alreadyLiked;
    }

    /**
     * Generated from protobuf field <code>bool alreadyLiked = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setAlreadyLiked($var)
    {
        GPBUtil::checkBool($var);
        $this->alreadyLiked = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 numberOfLikes = 9;</code>
     * @return int
     */
    public function getNumberOfLikes()
    {
        return $this->numberOfLikes;
    }

    /**
     * Generated from protobuf field <code>uint32 numberOfLikes = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setNumberOfLikes($var)
    {
        GPBUtil::checkUint32($var);
        $this->numberOfLikes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string body = 10;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>string body = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 created = 11;</code>
     * @return int
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Generated from protobuf field <code>uint32 created = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkUint32($var);
        $this->created = $var;

        return $this;
    }

}

