<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.CommentListView</code>
 */
class CommentListView extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Comment comments = 1;</code>
     */
    private $comments;
    /**
     * Generated from protobuf field <code>optional bool ifSetUserName = 2;</code>
     */
    protected $ifSetUserName = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Comment[] $comments
     *     @type bool $ifSetUserName
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Comment comments = 1;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Comment>
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Comment comments = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\Comment[] $var
     * @return $this
     */
    public function setComments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Comment::class);
        $this->comments = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool ifSetUserName = 2;</code>
     * @return bool
     */
    public function getIfSetUserName()
    {
        return isset($this->ifSetUserName) ? $this->ifSetUserName : false;
    }

    public function hasIfSetUserName()
    {
        return isset($this->ifSetUserName);
    }

    public function clearIfSetUserName()
    {
        unset($this->ifSetUserName);
    }

    /**
     * Generated from protobuf field <code>optional bool ifSetUserName = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIfSetUserName($var)
    {
        GPBUtil::checkBool($var);
        $this->ifSetUserName = $var;

        return $this;
    }

}

