<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.ErrorResult</code>
 */
class ErrorResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 action = 1;</code>
     */
    protected $action = 0;
    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.OSDefault englishPopup = 2;</code>
     */
    protected $englishPopup = null;
    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.OSDefault spanishPopup = 3;</code>
     */
    protected $spanishPopup = null;
    /**
     * Generated from protobuf field <code>string debugInfo = 4;</code>
     */
    protected $debugInfo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $action
     *     @type \App\Api\Protobuf\MangaPlus\Popup\OSDefault $englishPopup
     *     @type \App\Api\Protobuf\MangaPlus\Popup\OSDefault $spanishPopup
     *     @type string $debugInfo
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 action = 1;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>int32 action = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkInt32($var);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.OSDefault englishPopup = 2;</code>
     * @return \App\Api\Protobuf\MangaPlus\Popup\OSDefault|null
     */
    public function getEnglishPopup()
    {
        return $this->englishPopup;
    }

    public function hasEnglishPopup()
    {
        return isset($this->englishPopup);
    }

    public function clearEnglishPopup()
    {
        unset($this->englishPopup);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.OSDefault englishPopup = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\Popup\OSDefault $var
     * @return $this
     */
    public function setEnglishPopup($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Popup\OSDefault::class);
        $this->englishPopup = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.OSDefault spanishPopup = 3;</code>
     * @return \App\Api\Protobuf\MangaPlus\Popup\OSDefault|null
     */
    public function getSpanishPopup()
    {
        return $this->spanishPopup;
    }

    public function hasSpanishPopup()
    {
        return isset($this->spanishPopup);
    }

    public function clearSpanishPopup()
    {
        unset($this->spanishPopup);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.OSDefault spanishPopup = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\Popup\OSDefault $var
     * @return $this
     */
    public function setSpanishPopup($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Popup\OSDefault::class);
        $this->spanishPopup = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string debugInfo = 4;</code>
     * @return string
     */
    public function getDebugInfo()
    {
        return $this->debugInfo;
    }

    /**
     * Generated from protobuf field <code>string debugInfo = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDebugInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->debugInfo = $var;

        return $this;
    }

}

