<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.FeaturedTitlesView</code>
 */
class FeaturedTitlesView extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.MangaPlus.Banner mainBanner = 1;</code>
     */
    protected $mainBanner = null;
    /**
     * Generated from protobuf field <code>.MangaPlus.Banner subBanner_1 = 2;</code>
     */
    protected $subBanner_1 = null;
    /**
     * Generated from protobuf field <code>.MangaPlus.Banner subBanner_2 = 3;</code>
     */
    protected $subBanner_2 = null;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.FeaturedTitlesView.Contents contents = 4;</code>
     */
    private $contents;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Banner $mainBanner
     *     @type \App\Api\Protobuf\MangaPlus\Banner $subBanner_1
     *     @type \App\Api\Protobuf\MangaPlus\Banner $subBanner_2
     *     @type \App\Api\Protobuf\MangaPlus\FeaturedTitlesView\Contents[] $contents
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Banner mainBanner = 1;</code>
     * @return \App\Api\Protobuf\MangaPlus\Banner|null
     */
    public function getMainBanner()
    {
        return $this->mainBanner;
    }

    public function hasMainBanner()
    {
        return isset($this->mainBanner);
    }

    public function clearMainBanner()
    {
        unset($this->mainBanner);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Banner mainBanner = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\Banner $var
     * @return $this
     */
    public function setMainBanner($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Banner::class);
        $this->mainBanner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Banner subBanner_1 = 2;</code>
     * @return \App\Api\Protobuf\MangaPlus\Banner|null
     */
    public function getSubBanner1()
    {
        return $this->subBanner_1;
    }

    public function hasSubBanner1()
    {
        return isset($this->subBanner_1);
    }

    public function clearSubBanner1()
    {
        unset($this->subBanner_1);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Banner subBanner_1 = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\Banner $var
     * @return $this
     */
    public function setSubBanner1($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Banner::class);
        $this->subBanner_1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Banner subBanner_2 = 3;</code>
     * @return \App\Api\Protobuf\MangaPlus\Banner|null
     */
    public function getSubBanner2()
    {
        return $this->subBanner_2;
    }

    public function hasSubBanner2()
    {
        return isset($this->subBanner_2);
    }

    public function clearSubBanner2()
    {
        unset($this->subBanner_2);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Banner subBanner_2 = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\Banner $var
     * @return $this
     */
    public function setSubBanner2($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Banner::class);
        $this->subBanner_2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.FeaturedTitlesView.Contents contents = 4;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\FeaturedTitlesView\Contents>
     */
    public function getContents()
    {
        return $this->contents;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.FeaturedTitlesView.Contents contents = 4;</code>
     * @param \App\Api\Protobuf\MangaPlus\FeaturedTitlesView\Contents[] $var
     * @return $this
     */
    public function setContents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\FeaturedTitlesView\Contents::class);
        $this->contents = $arr;

        return $this;
    }

}

