<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.FeedbackView</code>
 */
class FeedbackView extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Feedback feedbackList = 1;</code>
     */
    private $feedbackList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Feedback[] $feedbackList
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Feedback feedbackList = 1;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Feedback>
     */
    public function getFeedbackList()
    {
        return $this->feedbackList;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Feedback feedbackList = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\Feedback[] $var
     * @return $this
     */
    public function setFeedbackList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Feedback::class);
        $this->feedbackList = $arr;

        return $this;
    }

}

