<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Feedback</code>
 */
class Feedback extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 timeStamp = 1;</code>
     */
    protected $timeStamp = 0;
    /**
     * Generated from protobuf field <code>string body = 2;</code>
     */
    protected $body = '';
    /**
     * Generated from protobuf field <code>int32 responseType = 3;</code>
     */
    protected $responseType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $timeStamp
     *     @type string $body
     *     @type int $responseType
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 timeStamp = 1;</code>
     * @return int
     */
    public function getTimeStamp()
    {
        return $this->timeStamp;
    }

    /**
     * Generated from protobuf field <code>uint32 timeStamp = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeStamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string body = 2;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>string body = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 responseType = 3;</code>
     * @return int
     */
    public function getResponseType()
    {
        return $this->responseType;
    }

    /**
     * Generated from protobuf field <code>int32 responseType = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseType($var)
    {
        GPBUtil::checkInt32($var);
        $this->responseType = $var;

        return $this;
    }

}

