<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.HomeView</code>
 */
class HomeView extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner topBanners = 1;</code>
     */
    private $topBanners;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.UpdatedTitleGroup groups = 2;</code>
     */
    private $groups;
    /**
     * Generated from protobuf field <code>.MangaPlus.Popup popup = 9;</code>
     */
    protected $popup = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Banner[] $topBanners
     *     @type \App\Api\Protobuf\MangaPlus\UpdatedTitleGroup[] $groups
     *     @type \App\Api\Protobuf\MangaPlus\Popup $popup
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner topBanners = 1;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Banner>
     */
    public function getTopBanners()
    {
        return $this->topBanners;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner topBanners = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\Banner[] $var
     * @return $this
     */
    public function setTopBanners($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Banner::class);
        $this->topBanners = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.UpdatedTitleGroup groups = 2;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\UpdatedTitleGroup>
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.UpdatedTitleGroup groups = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\UpdatedTitleGroup[] $var
     * @return $this
     */
    public function setGroups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\UpdatedTitleGroup::class);
        $this->groups = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup popup = 9;</code>
     * @return \App\Api\Protobuf\MangaPlus\Popup|null
     */
    public function getPopup()
    {
        return $this->popup;
    }

    public function hasPopup()
    {
        return isset($this->popup);
    }

    public function clearPopup()
    {
        unset($this->popup);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup popup = 9;</code>
     * @param \App\Api\Protobuf\MangaPlus\Popup $var
     * @return $this
     */
    public function setPopup($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Popup::class);
        $this->popup = $var;

        return $this;
    }

}

