<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.InitialView</code>
 */
class InitialView extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool gdprAgreementRequired = 1;</code>
     */
    protected $gdprAgreementRequired = null;
    /**
     * Generated from protobuf field <code>optional uint32 englishTitlesCount = 2;</code>
     */
    protected $englishTitlesCount = null;
    /**
     * Generated from protobuf field <code>optional uint32 spanishTitlesCount = 3;</code>
     */
    protected $spanishTitlesCount = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $gdprAgreementRequired
     *     @type int $englishTitlesCount
     *     @type int $spanishTitlesCount
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool gdprAgreementRequired = 1;</code>
     * @return bool
     */
    public function getGdprAgreementRequired()
    {
        return isset($this->gdprAgreementRequired) ? $this->gdprAgreementRequired : false;
    }

    public function hasGdprAgreementRequired()
    {
        return isset($this->gdprAgreementRequired);
    }

    public function clearGdprAgreementRequired()
    {
        unset($this->gdprAgreementRequired);
    }

    /**
     * Generated from protobuf field <code>optional bool gdprAgreementRequired = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setGdprAgreementRequired($var)
    {
        GPBUtil::checkBool($var);
        $this->gdprAgreementRequired = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 englishTitlesCount = 2;</code>
     * @return int
     */
    public function getEnglishTitlesCount()
    {
        return isset($this->englishTitlesCount) ? $this->englishTitlesCount : 0;
    }

    public function hasEnglishTitlesCount()
    {
        return isset($this->englishTitlesCount);
    }

    public function clearEnglishTitlesCount()
    {
        unset($this->englishTitlesCount);
    }

    /**
     * Generated from protobuf field <code>optional uint32 englishTitlesCount = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setEnglishTitlesCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->englishTitlesCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 spanishTitlesCount = 3;</code>
     * @return int
     */
    public function getSpanishTitlesCount()
    {
        return isset($this->spanishTitlesCount) ? $this->spanishTitlesCount : 0;
    }

    public function hasSpanishTitlesCount()
    {
        return isset($this->spanishTitlesCount);
    }

    public function clearSpanishTitlesCount()
    {
        unset($this->spanishTitlesCount);
    }

    /**
     * Generated from protobuf field <code>optional uint32 spanishTitlesCount = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSpanishTitlesCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->spanishTitlesCount = $var;

        return $this;
    }

}

