<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.LanguageVersion</code>
 */
class LanguageVersion extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 titleId = 1;</code>
     */
    protected $titleId = 0;
    /**
     * Generated from protobuf field <code>uint32 languageId = 2;</code>
     */
    protected $languageId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $titleId
     *     @type int $languageId
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 titleId = 1;</code>
     * @return int
     */
    public function getTitleId()
    {
        return $this->titleId;
    }

    /**
     * Generated from protobuf field <code>uint32 titleId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTitleId($var)
    {
        GPBUtil::checkUint32($var);
        $this->titleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 languageId = 2;</code>
     * @return int
     */
    public function getLanguageId()
    {
        return $this->languageId;
    }

    /**
     * Generated from protobuf field <code>uint32 languageId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLanguageId($var)
    {
        GPBUtil::checkUint32($var);
        $this->languageId = $var;

        return $this;
    }

}

