<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.MangaViewer</code>
 */
class MangaViewer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Page pages = 1;</code>
     */
    private $pages;
    /**
     * Generated from protobuf field <code>optional uint32 chapterId = 2;</code>
     */
    protected $chapterId = null;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter chapters = 3;</code>
     */
    private $chapters;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.Sns sns = 4;</code>
     */
    protected $sns = null;
    /**
     * Generated from protobuf field <code>optional string titleName = 5;</code>
     */
    protected $titleName = null;
    /**
     * Generated from protobuf field <code>optional string chapterName = 6;</code>
     */
    protected $chapterName = null;
    /**
     * Generated from protobuf field <code>optional uint32 numberOfComments = 7;</code>
     */
    protected $numberOfComments = null;
    /**
     * Generated from protobuf field <code>optional bool isVerticalOnly = 8;</code>
     */
    protected $isVerticalOnly = null;
    /**
     * Generated from protobuf field <code>optional uint32 titleId = 9;</code>
     */
    protected $titleId = null;
    /**
     * Generated from protobuf field <code>optional bool startFromRight = 10;</code>
     */
    protected $startFromRight = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Page[] $pages
     *     @type int $chapterId
     *     @type \App\Api\Protobuf\MangaPlus\Chapter[] $chapters
     *     @type \App\Api\Protobuf\MangaPlus\Sns $sns
     *     @type string $titleName
     *     @type string $chapterName
     *     @type int $numberOfComments
     *     @type bool $isVerticalOnly
     *     @type int $titleId
     *     @type bool $startFromRight
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Page pages = 1;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Page>
     */
    public function getPages()
    {
        return $this->pages;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Page pages = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\Page[] $var
     * @return $this
     */
    public function setPages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Page::class);
        $this->pages = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 chapterId = 2;</code>
     * @return int
     */
    public function getChapterId()
    {
        return isset($this->chapterId) ? $this->chapterId : 0;
    }

    public function hasChapterId()
    {
        return isset($this->chapterId);
    }

    public function clearChapterId()
    {
        unset($this->chapterId);
    }

    /**
     * Generated from protobuf field <code>optional uint32 chapterId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setChapterId($var)
    {
        GPBUtil::checkUint32($var);
        $this->chapterId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter chapters = 3;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Chapter>
     */
    public function getChapters()
    {
        return $this->chapters;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter chapters = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\Chapter[] $var
     * @return $this
     */
    public function setChapters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Chapter::class);
        $this->chapters = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Sns sns = 4;</code>
     * @return \App\Api\Protobuf\MangaPlus\Sns|null
     */
    public function getSns()
    {
        return $this->sns;
    }

    public function hasSns()
    {
        return isset($this->sns);
    }

    public function clearSns()
    {
        unset($this->sns);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Sns sns = 4;</code>
     * @param \App\Api\Protobuf\MangaPlus\Sns $var
     * @return $this
     */
    public function setSns($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Sns::class);
        $this->sns = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string titleName = 5;</code>
     * @return string
     */
    public function getTitleName()
    {
        return isset($this->titleName) ? $this->titleName : '';
    }

    public function hasTitleName()
    {
        return isset($this->titleName);
    }

    public function clearTitleName()
    {
        unset($this->titleName);
    }

    /**
     * Generated from protobuf field <code>optional string titleName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTitleName($var)
    {
        GPBUtil::checkString($var, True);
        $this->titleName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string chapterName = 6;</code>
     * @return string
     */
    public function getChapterName()
    {
        return isset($this->chapterName) ? $this->chapterName : '';
    }

    public function hasChapterName()
    {
        return isset($this->chapterName);
    }

    public function clearChapterName()
    {
        unset($this->chapterName);
    }

    /**
     * Generated from protobuf field <code>optional string chapterName = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setChapterName($var)
    {
        GPBUtil::checkString($var, True);
        $this->chapterName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 numberOfComments = 7;</code>
     * @return int
     */
    public function getNumberOfComments()
    {
        return isset($this->numberOfComments) ? $this->numberOfComments : 0;
    }

    public function hasNumberOfComments()
    {
        return isset($this->numberOfComments);
    }

    public function clearNumberOfComments()
    {
        unset($this->numberOfComments);
    }

    /**
     * Generated from protobuf field <code>optional uint32 numberOfComments = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setNumberOfComments($var)
    {
        GPBUtil::checkUint32($var);
        $this->numberOfComments = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool isVerticalOnly = 8;</code>
     * @return bool
     */
    public function getIsVerticalOnly()
    {
        return isset($this->isVerticalOnly) ? $this->isVerticalOnly : false;
    }

    public function hasIsVerticalOnly()
    {
        return isset($this->isVerticalOnly);
    }

    public function clearIsVerticalOnly()
    {
        unset($this->isVerticalOnly);
    }

    /**
     * Generated from protobuf field <code>optional bool isVerticalOnly = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsVerticalOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->isVerticalOnly = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 titleId = 9;</code>
     * @return int
     */
    public function getTitleId()
    {
        return isset($this->titleId) ? $this->titleId : 0;
    }

    public function hasTitleId()
    {
        return isset($this->titleId);
    }

    public function clearTitleId()
    {
        unset($this->titleId);
    }

    /**
     * Generated from protobuf field <code>optional uint32 titleId = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setTitleId($var)
    {
        GPBUtil::checkUint32($var);
        $this->titleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool startFromRight = 10;</code>
     * @return bool
     */
    public function getStartFromRight()
    {
        return isset($this->startFromRight) ? $this->startFromRight : false;
    }

    public function hasStartFromRight()
    {
        return isset($this->startFromRight);
    }

    public function clearStartFromRight()
    {
        unset($this->startFromRight);
    }

    /**
     * Generated from protobuf field <code>optional bool startFromRight = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setStartFromRight($var)
    {
        GPBUtil::checkBool($var);
        $this->startFromRight = $var;

        return $this;
    }

}

