<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.MovieReward</code>
 */
class MovieReward extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string imageUrl = 1;</code>
     */
    protected $imageUrl = '';
    /**
     * Generated from protobuf field <code>.MangaPlus.AdNetworkList advertisement = 2;</code>
     */
    protected $advertisement = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $imageUrl
     *     @type \App\Api\Protobuf\MangaPlus\AdNetworkList $advertisement
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string imageUrl = 1;</code>
     * @return string
     */
    public function getImageUrl()
    {
        return $this->imageUrl;
    }

    /**
     * Generated from protobuf field <code>string imageUrl = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->imageUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.AdNetworkList advertisement = 2;</code>
     * @return \App\Api\Protobuf\MangaPlus\AdNetworkList|null
     */
    public function getAdvertisement()
    {
        return $this->advertisement;
    }

    public function hasAdvertisement()
    {
        return isset($this->advertisement);
    }

    public function clearAdvertisement()
    {
        unset($this->advertisement);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.AdNetworkList advertisement = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\AdNetworkList $var
     * @return $this
     */
    public function setAdvertisement($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\AdNetworkList::class);
        $this->advertisement = $var;

        return $this;
    }

}

