<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Page</code>
 */
class Page extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .MangaPlus.Page.MangaPage mangaPage = 1;</code>
     */
    protected $mangaPage = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.Page.BannerList bannerList = 2;</code>
     */
    protected $bannerList = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.Page.LastPage lastPage = 3;</code>
     */
    protected $lastPage = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetworkList advertisement = 4;</code>
     */
    protected $advertisement = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Page\MangaPage $mangaPage
     *     @type \App\Api\Protobuf\MangaPlus\Page\BannerList $bannerList
     *     @type \App\Api\Protobuf\MangaPlus\Page\LastPage $lastPage
     *     @type \App\Api\Protobuf\MangaPlus\AdNetworkList $advertisement
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Page.MangaPage mangaPage = 1;</code>
     * @return \App\Api\Protobuf\MangaPlus\Page\MangaPage|null
     */
    public function getMangaPage()
    {
        return $this->mangaPage;
    }

    public function hasMangaPage()
    {
        return isset($this->mangaPage);
    }

    public function clearMangaPage()
    {
        unset($this->mangaPage);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Page.MangaPage mangaPage = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\Page\MangaPage $var
     * @return $this
     */
    public function setMangaPage($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Page\MangaPage::class);
        $this->mangaPage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Page.BannerList bannerList = 2;</code>
     * @return \App\Api\Protobuf\MangaPlus\Page\BannerList|null
     */
    public function getBannerList()
    {
        return $this->bannerList;
    }

    public function hasBannerList()
    {
        return isset($this->bannerList);
    }

    public function clearBannerList()
    {
        unset($this->bannerList);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Page.BannerList bannerList = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\Page\BannerList $var
     * @return $this
     */
    public function setBannerList($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Page\BannerList::class);
        $this->bannerList = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Page.LastPage lastPage = 3;</code>
     * @return \App\Api\Protobuf\MangaPlus\Page\LastPage|null
     */
    public function getLastPage()
    {
        return $this->lastPage;
    }

    public function hasLastPage()
    {
        return isset($this->lastPage);
    }

    public function clearLastPage()
    {
        unset($this->lastPage);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Page.LastPage lastPage = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\Page\LastPage $var
     * @return $this
     */
    public function setLastPage($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Page\LastPage::class);
        $this->lastPage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetworkList advertisement = 4;</code>
     * @return \App\Api\Protobuf\MangaPlus\AdNetworkList|null
     */
    public function getAdvertisement()
    {
        return $this->advertisement;
    }

    public function hasAdvertisement()
    {
        return isset($this->advertisement);
    }

    public function clearAdvertisement()
    {
        unset($this->advertisement);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetworkList advertisement = 4;</code>
     * @param \App\Api\Protobuf\MangaPlus\AdNetworkList $var
     * @return $this
     */
    public function setAdvertisement($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\AdNetworkList::class);
        $this->advertisement = $var;

        return $this;
    }

}

