<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Popup</code>
 */
class Popup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.OSDefault osDefault = 1;</code>
     */
    protected $osDefault = null;
    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.AppDefault appDefault = 2;</code>
     */
    protected $appDefault = null;
    /**
     * Generated from protobuf field <code>.MangaPlus.MovieReward movieReward = 3;</code>
     */
    protected $movieReward = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Popup\OSDefault $osDefault
     *     @type \App\Api\Protobuf\MangaPlus\Popup\AppDefault $appDefault
     *     @type \App\Api\Protobuf\MangaPlus\MovieReward $movieReward
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.OSDefault osDefault = 1;</code>
     * @return \App\Api\Protobuf\MangaPlus\Popup\OSDefault|null
     */
    public function getOsDefault()
    {
        return $this->osDefault;
    }

    public function hasOsDefault()
    {
        return isset($this->osDefault);
    }

    public function clearOsDefault()
    {
        unset($this->osDefault);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.OSDefault osDefault = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\Popup\OSDefault $var
     * @return $this
     */
    public function setOsDefault($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Popup\OSDefault::class);
        $this->osDefault = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.AppDefault appDefault = 2;</code>
     * @return \App\Api\Protobuf\MangaPlus\Popup\AppDefault|null
     */
    public function getAppDefault()
    {
        return $this->appDefault;
    }

    public function hasAppDefault()
    {
        return isset($this->appDefault);
    }

    public function clearAppDefault()
    {
        unset($this->appDefault);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Popup.AppDefault appDefault = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\Popup\AppDefault $var
     * @return $this
     */
    public function setAppDefault($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Popup\AppDefault::class);
        $this->appDefault = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.MovieReward movieReward = 3;</code>
     * @return \App\Api\Protobuf\MangaPlus\MovieReward|null
     */
    public function getMovieReward()
    {
        return $this->movieReward;
    }

    public function hasMovieReward()
    {
        return isset($this->movieReward);
    }

    public function clearMovieReward()
    {
        unset($this->movieReward);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.MovieReward movieReward = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\MovieReward $var
     * @return $this
     */
    public function setMovieReward($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\MovieReward::class);
        $this->movieReward = $var;

        return $this;
    }

}

