<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.ProfileSettingsView</code>
 */
class ProfileSettingsView extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.CommentIcon iconList = 1;</code>
     */
    private $iconList;
    /**
     * Generated from protobuf field <code>optional string userName = 2;</code>
     */
    protected $userName = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.CommentIcon myIcon = 3;</code>
     */
    protected $myIcon = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\CommentIcon[] $iconList
     *     @type string $userName
     *     @type \App\Api\Protobuf\MangaPlus\CommentIcon $myIcon
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.CommentIcon iconList = 1;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\CommentIcon>
     */
    public function getIconList()
    {
        return $this->iconList;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.CommentIcon iconList = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\CommentIcon[] $var
     * @return $this
     */
    public function setIconList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\CommentIcon::class);
        $this->iconList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string userName = 2;</code>
     * @return string
     */
    public function getUserName()
    {
        return isset($this->userName) ? $this->userName : '';
    }

    public function hasUserName()
    {
        return isset($this->userName);
    }

    public function clearUserName()
    {
        unset($this->userName);
    }

    /**
     * Generated from protobuf field <code>optional string userName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->userName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.CommentIcon myIcon = 3;</code>
     * @return \App\Api\Protobuf\MangaPlus\CommentIcon|null
     */
    public function getMyIcon()
    {
        return $this->myIcon;
    }

    public function hasMyIcon()
    {
        return isset($this->myIcon);
    }

    public function clearMyIcon()
    {
        unset($this->myIcon);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.CommentIcon myIcon = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\CommentIcon $var
     * @return $this
     */
    public function setMyIcon($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\CommentIcon::class);
        $this->myIcon = $var;

        return $this;
    }

}

