<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.RegistrationData</code>
 */
class RegistrationData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string deviceSecret = 1;</code>
     */
    protected $deviceSecret = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $deviceSecret
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string deviceSecret = 1;</code>
     * @return string
     */
    public function getDeviceSecret()
    {
        return $this->deviceSecret;
    }

    /**
     * Generated from protobuf field <code>string deviceSecret = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->deviceSecret = $var;

        return $this;
    }

}

