<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .MangaPlus.SuccessResult success = 1;</code>
     */
    protected $success = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.ErrorResult error = 2;</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\SuccessResult $success
     *     @type \App\Api\Protobuf\MangaPlus\ErrorResult $error
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.SuccessResult success = 1;</code>
     * @return \App\Api\Protobuf\MangaPlus\SuccessResult|null
     */
    public function getSuccess()
    {
        return $this->success;
    }

    public function hasSuccess()
    {
        return isset($this->success);
    }

    public function clearSuccess()
    {
        unset($this->success);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.SuccessResult success = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\SuccessResult $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\SuccessResult::class);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.ErrorResult error = 2;</code>
     * @return \App\Api\Protobuf\MangaPlus\ErrorResult|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.ErrorResult error = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\ErrorResult $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\ErrorResult::class);
        $this->error = $var;

        return $this;
    }

}

