<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.ServiceAnnouncementsView</code>
 */
class ServiceAnnouncementsView extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.ServiceAnnouncement serviceAnnouncements = 1;</code>
     */
    private $serviceAnnouncements;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\ServiceAnnouncement[] $serviceAnnouncements
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.ServiceAnnouncement serviceAnnouncements = 1;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\ServiceAnnouncement>
     */
    public function getServiceAnnouncements()
    {
        return $this->serviceAnnouncements;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.ServiceAnnouncement serviceAnnouncements = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\ServiceAnnouncement[] $var
     * @return $this
     */
    public function setServiceAnnouncements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\ServiceAnnouncement::class);
        $this->serviceAnnouncements = $arr;

        return $this;
    }

}

