<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.SettingsView</code>
 */
class SettingsView extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.MangaPlus.CommentIcon myIcon = 1;</code>
     */
    protected $myIcon = null;
    /**
     * Generated from protobuf field <code>string userName = 2;</code>
     */
    protected $userName = '';
    /**
     * Generated from protobuf field <code>bool noticeOfNewsAndEvents = 3;</code>
     */
    protected $noticeOfNewsAndEvents = false;
    /**
     * Generated from protobuf field <code>bool noticeOfUpdatesOfSubscribedTitles = 4;</code>
     */
    protected $noticeOfUpdatesOfSubscribedTitles = false;
    /**
     * Generated from protobuf field <code>uint32 englishTitlesCount = 5;</code>
     */
    protected $englishTitlesCount = 0;
    /**
     * Generated from protobuf field <code>uint32 spanishTitlesCount = 6;</code>
     */
    protected $spanishTitlesCount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\CommentIcon $myIcon
     *     @type string $userName
     *     @type bool $noticeOfNewsAndEvents
     *     @type bool $noticeOfUpdatesOfSubscribedTitles
     *     @type int $englishTitlesCount
     *     @type int $spanishTitlesCount
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.CommentIcon myIcon = 1;</code>
     * @return \App\Api\Protobuf\MangaPlus\CommentIcon|null
     */
    public function getMyIcon()
    {
        return $this->myIcon;
    }

    public function hasMyIcon()
    {
        return isset($this->myIcon);
    }

    public function clearMyIcon()
    {
        unset($this->myIcon);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.CommentIcon myIcon = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\CommentIcon $var
     * @return $this
     */
    public function setMyIcon($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\CommentIcon::class);
        $this->myIcon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userName = 2;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->userName;
    }

    /**
     * Generated from protobuf field <code>string userName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->userName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool noticeOfNewsAndEvents = 3;</code>
     * @return bool
     */
    public function getNoticeOfNewsAndEvents()
    {
        return $this->noticeOfNewsAndEvents;
    }

    /**
     * Generated from protobuf field <code>bool noticeOfNewsAndEvents = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setNoticeOfNewsAndEvents($var)
    {
        GPBUtil::checkBool($var);
        $this->noticeOfNewsAndEvents = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool noticeOfUpdatesOfSubscribedTitles = 4;</code>
     * @return bool
     */
    public function getNoticeOfUpdatesOfSubscribedTitles()
    {
        return $this->noticeOfUpdatesOfSubscribedTitles;
    }

    /**
     * Generated from protobuf field <code>bool noticeOfUpdatesOfSubscribedTitles = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setNoticeOfUpdatesOfSubscribedTitles($var)
    {
        GPBUtil::checkBool($var);
        $this->noticeOfUpdatesOfSubscribedTitles = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 englishTitlesCount = 5;</code>
     * @return int
     */
    public function getEnglishTitlesCount()
    {
        return $this->englishTitlesCount;
    }

    /**
     * Generated from protobuf field <code>uint32 englishTitlesCount = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setEnglishTitlesCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->englishTitlesCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 spanishTitlesCount = 6;</code>
     * @return int
     */
    public function getSpanishTitlesCount()
    {
        return $this->spanishTitlesCount;
    }

    /**
     * Generated from protobuf field <code>uint32 spanishTitlesCount = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSpanishTitlesCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->spanishTitlesCount = $var;

        return $this;
    }

}

