<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.SuccessResult</code>
 */
class SuccessResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool isFeaturedUpdated = 1;</code>
     */
    protected $isFeaturedUpdated = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.RegistrationData registerationData = 2;</code>
     */
    protected $registerationData = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.HomeView homeView = 3;</code>
     */
    protected $homeView = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.FeaturedTitlesView featuredTitlesView = 4;</code>
     */
    protected $featuredTitlesView = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.AllTitlesView allTitlesView = 5;</code>
     */
    protected $allTitlesView = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.TitleRankingView titleRankingView = 6;</code>
     */
    protected $titleRankingView = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.SubscribedTitlesView subscribedTitlesView = 7;</code>
     */
    protected $subscribedTitlesView = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.TitleDetailView titleDetailView = 8;</code>
     */
    protected $titleDetailView = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.CommentListView commentListView = 9;</code>
     */
    protected $commentListView = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.MangaViewer mangaViewer = 10;</code>
     */
    protected $mangaViewer = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.WebHomeView webHomeView = 11;</code>
     */
    protected $webHomeView = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.SettingsView settingsView = 12;</code>
     */
    protected $settingsView = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.ProfileSettingsView profileSettingsView = 13;</code>
     */
    protected $profileSettingsView = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.UpdateProfileResultView updateProfileResultView = 14;</code>
     */
    protected $updateProfileResultView = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.ServiceAnnouncementsView serviceAnnouncementsView = 15;</code>
     */
    protected $serviceAnnouncementsView = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.InitialView initialView = 16;</code>
     */
    protected $initialView = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.FeedbackView feedbackView = 17;</code>
     */
    protected $feedbackView = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.AllTitlesViewV2 allTitlesViewV2 = 25;</code>
     */
    protected $allTitlesViewV2 = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $isFeaturedUpdated
     *     @type \App\Api\Protobuf\MangaPlus\RegistrationData $registerationData
     *     @type \App\Api\Protobuf\MangaPlus\HomeView $homeView
     *     @type \App\Api\Protobuf\MangaPlus\FeaturedTitlesView $featuredTitlesView
     *     @type \App\Api\Protobuf\MangaPlus\AllTitlesView $allTitlesView
     *     @type \App\Api\Protobuf\MangaPlus\TitleRankingView $titleRankingView
     *     @type \App\Api\Protobuf\MangaPlus\SubscribedTitlesView $subscribedTitlesView
     *     @type \App\Api\Protobuf\MangaPlus\TitleDetailView $titleDetailView
     *     @type \App\Api\Protobuf\MangaPlus\CommentListView $commentListView
     *     @type \App\Api\Protobuf\MangaPlus\MangaViewer $mangaViewer
     *     @type \App\Api\Protobuf\MangaPlus\WebHomeView $webHomeView
     *     @type \App\Api\Protobuf\MangaPlus\SettingsView $settingsView
     *     @type \App\Api\Protobuf\MangaPlus\ProfileSettingsView $profileSettingsView
     *     @type \App\Api\Protobuf\MangaPlus\UpdateProfileResultView $updateProfileResultView
     *     @type \App\Api\Protobuf\MangaPlus\ServiceAnnouncementsView $serviceAnnouncementsView
     *     @type \App\Api\Protobuf\MangaPlus\InitialView $initialView
     *     @type \App\Api\Protobuf\MangaPlus\FeedbackView $feedbackView
     *     @type \App\Api\Protobuf\MangaPlus\AllTitlesViewV2 $allTitlesViewV2
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool isFeaturedUpdated = 1;</code>
     * @return bool
     */
    public function getIsFeaturedUpdated()
    {
        return isset($this->isFeaturedUpdated) ? $this->isFeaturedUpdated : false;
    }

    public function hasIsFeaturedUpdated()
    {
        return isset($this->isFeaturedUpdated);
    }

    public function clearIsFeaturedUpdated()
    {
        unset($this->isFeaturedUpdated);
    }

    /**
     * Generated from protobuf field <code>optional bool isFeaturedUpdated = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFeaturedUpdated($var)
    {
        GPBUtil::checkBool($var);
        $this->isFeaturedUpdated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.RegistrationData registerationData = 2;</code>
     * @return \App\Api\Protobuf\MangaPlus\RegistrationData|null
     */
    public function getRegisterationData()
    {
        return $this->registerationData;
    }

    public function hasRegisterationData()
    {
        return isset($this->registerationData);
    }

    public function clearRegisterationData()
    {
        unset($this->registerationData);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.RegistrationData registerationData = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\RegistrationData $var
     * @return $this
     */
    public function setRegisterationData($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\RegistrationData::class);
        $this->registerationData = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.HomeView homeView = 3;</code>
     * @return \App\Api\Protobuf\MangaPlus\HomeView|null
     */
    public function getHomeView()
    {
        return $this->homeView;
    }

    public function hasHomeView()
    {
        return isset($this->homeView);
    }

    public function clearHomeView()
    {
        unset($this->homeView);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.HomeView homeView = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\HomeView $var
     * @return $this
     */
    public function setHomeView($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\HomeView::class);
        $this->homeView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.FeaturedTitlesView featuredTitlesView = 4;</code>
     * @return \App\Api\Protobuf\MangaPlus\FeaturedTitlesView|null
     */
    public function getFeaturedTitlesView()
    {
        return $this->featuredTitlesView;
    }

    public function hasFeaturedTitlesView()
    {
        return isset($this->featuredTitlesView);
    }

    public function clearFeaturedTitlesView()
    {
        unset($this->featuredTitlesView);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.FeaturedTitlesView featuredTitlesView = 4;</code>
     * @param \App\Api\Protobuf\MangaPlus\FeaturedTitlesView $var
     * @return $this
     */
    public function setFeaturedTitlesView($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\FeaturedTitlesView::class);
        $this->featuredTitlesView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AllTitlesView allTitlesView = 5;</code>
     * @return \App\Api\Protobuf\MangaPlus\AllTitlesView|null
     */
    public function getAllTitlesView()
    {
        return $this->allTitlesView;
    }

    public function hasAllTitlesView()
    {
        return isset($this->allTitlesView);
    }

    public function clearAllTitlesView()
    {
        unset($this->allTitlesView);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AllTitlesView allTitlesView = 5;</code>
     * @param \App\Api\Protobuf\MangaPlus\AllTitlesView $var
     * @return $this
     */
    public function setAllTitlesView($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\AllTitlesView::class);
        $this->allTitlesView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.TitleRankingView titleRankingView = 6;</code>
     * @return \App\Api\Protobuf\MangaPlus\TitleRankingView|null
     */
    public function getTitleRankingView()
    {
        return $this->titleRankingView;
    }

    public function hasTitleRankingView()
    {
        return isset($this->titleRankingView);
    }

    public function clearTitleRankingView()
    {
        unset($this->titleRankingView);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.TitleRankingView titleRankingView = 6;</code>
     * @param \App\Api\Protobuf\MangaPlus\TitleRankingView $var
     * @return $this
     */
    public function setTitleRankingView($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\TitleRankingView::class);
        $this->titleRankingView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.SubscribedTitlesView subscribedTitlesView = 7;</code>
     * @return \App\Api\Protobuf\MangaPlus\SubscribedTitlesView|null
     */
    public function getSubscribedTitlesView()
    {
        return $this->subscribedTitlesView;
    }

    public function hasSubscribedTitlesView()
    {
        return isset($this->subscribedTitlesView);
    }

    public function clearSubscribedTitlesView()
    {
        unset($this->subscribedTitlesView);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.SubscribedTitlesView subscribedTitlesView = 7;</code>
     * @param \App\Api\Protobuf\MangaPlus\SubscribedTitlesView $var
     * @return $this
     */
    public function setSubscribedTitlesView($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\SubscribedTitlesView::class);
        $this->subscribedTitlesView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.TitleDetailView titleDetailView = 8;</code>
     * @return \App\Api\Protobuf\MangaPlus\TitleDetailView|null
     */
    public function getTitleDetailView()
    {
        return $this->titleDetailView;
    }

    public function hasTitleDetailView()
    {
        return isset($this->titleDetailView);
    }

    public function clearTitleDetailView()
    {
        unset($this->titleDetailView);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.TitleDetailView titleDetailView = 8;</code>
     * @param \App\Api\Protobuf\MangaPlus\TitleDetailView $var
     * @return $this
     */
    public function setTitleDetailView($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\TitleDetailView::class);
        $this->titleDetailView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.CommentListView commentListView = 9;</code>
     * @return \App\Api\Protobuf\MangaPlus\CommentListView|null
     */
    public function getCommentListView()
    {
        return $this->commentListView;
    }

    public function hasCommentListView()
    {
        return isset($this->commentListView);
    }

    public function clearCommentListView()
    {
        unset($this->commentListView);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.CommentListView commentListView = 9;</code>
     * @param \App\Api\Protobuf\MangaPlus\CommentListView $var
     * @return $this
     */
    public function setCommentListView($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\CommentListView::class);
        $this->commentListView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.MangaViewer mangaViewer = 10;</code>
     * @return \App\Api\Protobuf\MangaPlus\MangaViewer|null
     */
    public function getMangaViewer()
    {
        return $this->mangaViewer;
    }

    public function hasMangaViewer()
    {
        return isset($this->mangaViewer);
    }

    public function clearMangaViewer()
    {
        unset($this->mangaViewer);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.MangaViewer mangaViewer = 10;</code>
     * @param \App\Api\Protobuf\MangaPlus\MangaViewer $var
     * @return $this
     */
    public function setMangaViewer($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\MangaViewer::class);
        $this->mangaViewer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.WebHomeView webHomeView = 11;</code>
     * @return \App\Api\Protobuf\MangaPlus\WebHomeView|null
     */
    public function getWebHomeView()
    {
        return $this->webHomeView;
    }

    public function hasWebHomeView()
    {
        return isset($this->webHomeView);
    }

    public function clearWebHomeView()
    {
        unset($this->webHomeView);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.WebHomeView webHomeView = 11;</code>
     * @param \App\Api\Protobuf\MangaPlus\WebHomeView $var
     * @return $this
     */
    public function setWebHomeView($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\WebHomeView::class);
        $this->webHomeView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.SettingsView settingsView = 12;</code>
     * @return \App\Api\Protobuf\MangaPlus\SettingsView|null
     */
    public function getSettingsView()
    {
        return $this->settingsView;
    }

    public function hasSettingsView()
    {
        return isset($this->settingsView);
    }

    public function clearSettingsView()
    {
        unset($this->settingsView);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.SettingsView settingsView = 12;</code>
     * @param \App\Api\Protobuf\MangaPlus\SettingsView $var
     * @return $this
     */
    public function setSettingsView($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\SettingsView::class);
        $this->settingsView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.ProfileSettingsView profileSettingsView = 13;</code>
     * @return \App\Api\Protobuf\MangaPlus\ProfileSettingsView|null
     */
    public function getProfileSettingsView()
    {
        return $this->profileSettingsView;
    }

    public function hasProfileSettingsView()
    {
        return isset($this->profileSettingsView);
    }

    public function clearProfileSettingsView()
    {
        unset($this->profileSettingsView);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.ProfileSettingsView profileSettingsView = 13;</code>
     * @param \App\Api\Protobuf\MangaPlus\ProfileSettingsView $var
     * @return $this
     */
    public function setProfileSettingsView($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\ProfileSettingsView::class);
        $this->profileSettingsView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.UpdateProfileResultView updateProfileResultView = 14;</code>
     * @return \App\Api\Protobuf\MangaPlus\UpdateProfileResultView|null
     */
    public function getUpdateProfileResultView()
    {
        return $this->updateProfileResultView;
    }

    public function hasUpdateProfileResultView()
    {
        return isset($this->updateProfileResultView);
    }

    public function clearUpdateProfileResultView()
    {
        unset($this->updateProfileResultView);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.UpdateProfileResultView updateProfileResultView = 14;</code>
     * @param \App\Api\Protobuf\MangaPlus\UpdateProfileResultView $var
     * @return $this
     */
    public function setUpdateProfileResultView($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\UpdateProfileResultView::class);
        $this->updateProfileResultView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.ServiceAnnouncementsView serviceAnnouncementsView = 15;</code>
     * @return \App\Api\Protobuf\MangaPlus\ServiceAnnouncementsView|null
     */
    public function getServiceAnnouncementsView()
    {
        return $this->serviceAnnouncementsView;
    }

    public function hasServiceAnnouncementsView()
    {
        return isset($this->serviceAnnouncementsView);
    }

    public function clearServiceAnnouncementsView()
    {
        unset($this->serviceAnnouncementsView);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.ServiceAnnouncementsView serviceAnnouncementsView = 15;</code>
     * @param \App\Api\Protobuf\MangaPlus\ServiceAnnouncementsView $var
     * @return $this
     */
    public function setServiceAnnouncementsView($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\ServiceAnnouncementsView::class);
        $this->serviceAnnouncementsView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.InitialView initialView = 16;</code>
     * @return \App\Api\Protobuf\MangaPlus\InitialView|null
     */
    public function getInitialView()
    {
        return $this->initialView;
    }

    public function hasInitialView()
    {
        return isset($this->initialView);
    }

    public function clearInitialView()
    {
        unset($this->initialView);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.InitialView initialView = 16;</code>
     * @param \App\Api\Protobuf\MangaPlus\InitialView $var
     * @return $this
     */
    public function setInitialView($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\InitialView::class);
        $this->initialView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.FeedbackView feedbackView = 17;</code>
     * @return \App\Api\Protobuf\MangaPlus\FeedbackView|null
     */
    public function getFeedbackView()
    {
        return $this->feedbackView;
    }

    public function hasFeedbackView()
    {
        return isset($this->feedbackView);
    }

    public function clearFeedbackView()
    {
        unset($this->feedbackView);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.FeedbackView feedbackView = 17;</code>
     * @param \App\Api\Protobuf\MangaPlus\FeedbackView $var
     * @return $this
     */
    public function setFeedbackView($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\FeedbackView::class);
        $this->feedbackView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AllTitlesViewV2 allTitlesViewV2 = 25;</code>
     * @return \App\Api\Protobuf\MangaPlus\AllTitlesViewV2|null
     */
    public function getAllTitlesViewV2()
    {
        return $this->allTitlesViewV2;
    }

    public function hasAllTitlesViewV2()
    {
        return isset($this->allTitlesViewV2);
    }

    public function clearAllTitlesViewV2()
    {
        unset($this->allTitlesViewV2);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AllTitlesViewV2 allTitlesViewV2 = 25;</code>
     * @param \App\Api\Protobuf\MangaPlus\AllTitlesViewV2 $var
     * @return $this
     */
    public function setAllTitlesViewV2($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\AllTitlesViewV2::class);
        $this->allTitlesViewV2 = $var;

        return $this;
    }

}

