<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Tag</code>
 */
class Tag extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string tag = 1;</code>
     */
    protected $tag = null;
    /**
     * Generated from protobuf field <code>optional string slug = 2;</code>
     */
    protected $slug = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tag
     *     @type string $slug
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string tag = 1;</code>
     * @return string
     */
    public function getTag()
    {
        return isset($this->tag) ? $this->tag : '';
    }

    public function hasTag()
    {
        return isset($this->tag);
    }

    public function clearTag()
    {
        unset($this->tag);
    }

    /**
     * Generated from protobuf field <code>optional string tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string slug = 2;</code>
     * @return string
     */
    public function getSlug()
    {
        return isset($this->slug) ? $this->slug : '';
    }

    public function hasSlug()
    {
        return isset($this->slug);
    }

    public function clearSlug()
    {
        unset($this->slug);
    }

    /**
     * Generated from protobuf field <code>optional string slug = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSlug($var)
    {
        GPBUtil::checkString($var, True);
        $this->slug = $var;

        return $this;
    }

}

