<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.TitleDetailView</code>
 */
class TitleDetailView extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .MangaPlus.Title title = 1;</code>
     */
    protected $title = null;
    /**
     * Generated from protobuf field <code>optional string titleImageUrl = 2;</code>
     */
    protected $titleImageUrl = null;
    /**
     * Generated from protobuf field <code>optional string overview = 3;</code>
     */
    protected $overview = null;
    /**
     * Generated from protobuf field <code>optional string backgroundImageUrl = 4;</code>
     */
    protected $backgroundImageUrl = null;
    /**
     * Generated from protobuf field <code>optional uint32 nextTimeStamp = 5;</code>
     */
    protected $nextTimeStamp = null;
    /**
     * Generated from protobuf field <code>optional int32 updateTiming = 6;</code>
     */
    protected $updateTiming = null;
    /**
     * Generated from protobuf field <code>optional string viewingPeriodDescription = 7;</code>
     */
    protected $viewingPeriodDescription = null;
    /**
     * Generated from protobuf field <code>optional string nonAppearanceInfo = 8;</code>
     */
    protected $nonAppearanceInfo = null;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter firstChapterList = 9;</code>
     */
    private $firstChapterList;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter lastChapterList = 10;</code>
     */
    private $lastChapterList;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner banners = 11;</code>
     */
    private $banners;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title recommendedTitleList = 12;</code>
     */
    private $recommendedTitleList;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.Sns sns = 13;</code>
     */
    protected $sns = null;
    /**
     * Generated from protobuf field <code>optional bool isSimulReleased = 14;</code>
     */
    protected $isSimulReleased = null;
    /**
     * Generated from protobuf field <code>optional bool isSubscribed = 15;</code>
     */
    protected $isSubscribed = null;
    /**
     * Generated from protobuf field <code>optional int32 rating = 16;</code>
     */
    protected $rating = null;
    /**
     * Generated from protobuf field <code>optional bool chaptersDescending = 17;</code>
     */
    protected $chaptersDescending = null;
    /**
     * Generated from protobuf field <code>optional uint32 numberOfViews = 18;</code>
     */
    protected $numberOfViews = null;
    /**
     * repeated PublisherItem publisherItems = 19;
     *
     * Generated from protobuf field <code>repeated .MangaPlus.Banner titleBanners = 20;</code>
     */
    private $titleBanners;
    /**
     * optional UserTickets userTickets = 21;
     *
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter ticketChapterList = 22;</code>
     */
    private $ticketChapterList;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title ticketTitleList = 23;</code>
     */
    private $ticketTitleList;
    /**
     * Generated from protobuf field <code>optional bool hasChaptersBetween = 24;</code>
     */
    protected $hasChaptersBetween = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.Banner publisherBanner = 25;</code>
     */
    protected $publisherBanner = null;
    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetworkList advertisement = 26;</code>
     */
    protected $advertisement = null;
    /**
     * repeated TitleLanguages titleLanguages = 27;
     *
     * Generated from protobuf field <code>repeated .MangaPlus.TitleDetailView.ChapterGroup chapterListGroup = 28;</code>
     */
    private $chapterListGroup;
    /**
     * optional FreeViewDialogue freeViewDialogue = 29;
     *
     * Generated from protobuf field <code>optional string regionCode = 30;</code>
     */
    protected $regionCode = null;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Tag tags = 31;</code>
     */
    private $tags;
    /**
     * optional TitleLabels titleLabels = 32;
     * optional Subscription subscription = 33;
     *
     * Generated from protobuf field <code>optional .MangaPlus.Label label = 34;</code>
     */
    protected $label = null;
    /**
     * optional MetaInfo metaInfo = 36;
     *
     * Generated from protobuf field <code>optional bool isFirstTimeFree = 35;</code>
     */
    protected $isFirstTimeFree = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Title $title
     *     @type string $titleImageUrl
     *     @type string $overview
     *     @type string $backgroundImageUrl
     *     @type int $nextTimeStamp
     *     @type int $updateTiming
     *     @type string $viewingPeriodDescription
     *     @type string $nonAppearanceInfo
     *     @type \App\Api\Protobuf\MangaPlus\Chapter[] $firstChapterList
     *     @type \App\Api\Protobuf\MangaPlus\Chapter[] $lastChapterList
     *     @type \App\Api\Protobuf\MangaPlus\Banner[] $banners
     *     @type \App\Api\Protobuf\MangaPlus\Title[] $recommendedTitleList
     *     @type \App\Api\Protobuf\MangaPlus\Sns $sns
     *     @type bool $isSimulReleased
     *     @type bool $isSubscribed
     *     @type int $rating
     *     @type bool $chaptersDescending
     *     @type int $numberOfViews
     *     @type \App\Api\Protobuf\MangaPlus\Banner[] $titleBanners
     *           repeated PublisherItem publisherItems = 19;
     *     @type \App\Api\Protobuf\MangaPlus\Chapter[] $ticketChapterList
     *           optional UserTickets userTickets = 21;
     *     @type \App\Api\Protobuf\MangaPlus\Title[] $ticketTitleList
     *     @type bool $hasChaptersBetween
     *     @type \App\Api\Protobuf\MangaPlus\Banner $publisherBanner
     *     @type \App\Api\Protobuf\MangaPlus\AdNetworkList $advertisement
     *     @type \App\Api\Protobuf\MangaPlus\TitleDetailView\ChapterGroup[] $chapterListGroup
     *           repeated TitleLanguages titleLanguages = 27;
     *     @type string $regionCode
     *           optional FreeViewDialogue freeViewDialogue = 29;
     *     @type \App\Api\Protobuf\MangaPlus\Tag[] $tags
     *     @type \App\Api\Protobuf\MangaPlus\Label $label
     *           optional TitleLabels titleLabels = 32;
     *           optional Subscription subscription = 33;
     *     @type bool $isFirstTimeFree
     *           optional MetaInfo metaInfo = 36;
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Title title = 1;</code>
     * @return \App\Api\Protobuf\MangaPlus\Title|null
     */
    public function getTitle()
    {
        return $this->title;
    }

    public function hasTitle()
    {
        return isset($this->title);
    }

    public function clearTitle()
    {
        unset($this->title);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Title title = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\Title $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Title::class);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string titleImageUrl = 2;</code>
     * @return string
     */
    public function getTitleImageUrl()
    {
        return isset($this->titleImageUrl) ? $this->titleImageUrl : '';
    }

    public function hasTitleImageUrl()
    {
        return isset($this->titleImageUrl);
    }

    public function clearTitleImageUrl()
    {
        unset($this->titleImageUrl);
    }

    /**
     * Generated from protobuf field <code>optional string titleImageUrl = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitleImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->titleImageUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string overview = 3;</code>
     * @return string
     */
    public function getOverview()
    {
        return isset($this->overview) ? $this->overview : '';
    }

    public function hasOverview()
    {
        return isset($this->overview);
    }

    public function clearOverview()
    {
        unset($this->overview);
    }

    /**
     * Generated from protobuf field <code>optional string overview = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOverview($var)
    {
        GPBUtil::checkString($var, True);
        $this->overview = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string backgroundImageUrl = 4;</code>
     * @return string
     */
    public function getBackgroundImageUrl()
    {
        return isset($this->backgroundImageUrl) ? $this->backgroundImageUrl : '';
    }

    public function hasBackgroundImageUrl()
    {
        return isset($this->backgroundImageUrl);
    }

    public function clearBackgroundImageUrl()
    {
        unset($this->backgroundImageUrl);
    }

    /**
     * Generated from protobuf field <code>optional string backgroundImageUrl = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBackgroundImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->backgroundImageUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 nextTimeStamp = 5;</code>
     * @return int
     */
    public function getNextTimeStamp()
    {
        return isset($this->nextTimeStamp) ? $this->nextTimeStamp : 0;
    }

    public function hasNextTimeStamp()
    {
        return isset($this->nextTimeStamp);
    }

    public function clearNextTimeStamp()
    {
        unset($this->nextTimeStamp);
    }

    /**
     * Generated from protobuf field <code>optional uint32 nextTimeStamp = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setNextTimeStamp($var)
    {
        GPBUtil::checkUint32($var);
        $this->nextTimeStamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 updateTiming = 6;</code>
     * @return int
     */
    public function getUpdateTiming()
    {
        return isset($this->updateTiming) ? $this->updateTiming : 0;
    }

    public function hasUpdateTiming()
    {
        return isset($this->updateTiming);
    }

    public function clearUpdateTiming()
    {
        unset($this->updateTiming);
    }

    /**
     * Generated from protobuf field <code>optional int32 updateTiming = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdateTiming($var)
    {
        GPBUtil::checkInt32($var);
        $this->updateTiming = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string viewingPeriodDescription = 7;</code>
     * @return string
     */
    public function getViewingPeriodDescription()
    {
        return isset($this->viewingPeriodDescription) ? $this->viewingPeriodDescription : '';
    }

    public function hasViewingPeriodDescription()
    {
        return isset($this->viewingPeriodDescription);
    }

    public function clearViewingPeriodDescription()
    {
        unset($this->viewingPeriodDescription);
    }

    /**
     * Generated from protobuf field <code>optional string viewingPeriodDescription = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setViewingPeriodDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->viewingPeriodDescription = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string nonAppearanceInfo = 8;</code>
     * @return string
     */
    public function getNonAppearanceInfo()
    {
        return isset($this->nonAppearanceInfo) ? $this->nonAppearanceInfo : '';
    }

    public function hasNonAppearanceInfo()
    {
        return isset($this->nonAppearanceInfo);
    }

    public function clearNonAppearanceInfo()
    {
        unset($this->nonAppearanceInfo);
    }

    /**
     * Generated from protobuf field <code>optional string nonAppearanceInfo = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setNonAppearanceInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->nonAppearanceInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter firstChapterList = 9;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Chapter>
     */
    public function getFirstChapterList()
    {
        return $this->firstChapterList;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter firstChapterList = 9;</code>
     * @param \App\Api\Protobuf\MangaPlus\Chapter[] $var
     * @return $this
     */
    public function setFirstChapterList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Chapter::class);
        $this->firstChapterList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter lastChapterList = 10;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Chapter>
     */
    public function getLastChapterList()
    {
        return $this->lastChapterList;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter lastChapterList = 10;</code>
     * @param \App\Api\Protobuf\MangaPlus\Chapter[] $var
     * @return $this
     */
    public function setLastChapterList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Chapter::class);
        $this->lastChapterList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner banners = 11;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Banner>
     */
    public function getBanners()
    {
        return $this->banners;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner banners = 11;</code>
     * @param \App\Api\Protobuf\MangaPlus\Banner[] $var
     * @return $this
     */
    public function setBanners($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Banner::class);
        $this->banners = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title recommendedTitleList = 12;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Title>
     */
    public function getRecommendedTitleList()
    {
        return $this->recommendedTitleList;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title recommendedTitleList = 12;</code>
     * @param \App\Api\Protobuf\MangaPlus\Title[] $var
     * @return $this
     */
    public function setRecommendedTitleList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Title::class);
        $this->recommendedTitleList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Sns sns = 13;</code>
     * @return \App\Api\Protobuf\MangaPlus\Sns|null
     */
    public function getSns()
    {
        return $this->sns;
    }

    public function hasSns()
    {
        return isset($this->sns);
    }

    public function clearSns()
    {
        unset($this->sns);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Sns sns = 13;</code>
     * @param \App\Api\Protobuf\MangaPlus\Sns $var
     * @return $this
     */
    public function setSns($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Sns::class);
        $this->sns = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool isSimulReleased = 14;</code>
     * @return bool
     */
    public function getIsSimulReleased()
    {
        return isset($this->isSimulReleased) ? $this->isSimulReleased : false;
    }

    public function hasIsSimulReleased()
    {
        return isset($this->isSimulReleased);
    }

    public function clearIsSimulReleased()
    {
        unset($this->isSimulReleased);
    }

    /**
     * Generated from protobuf field <code>optional bool isSimulReleased = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSimulReleased($var)
    {
        GPBUtil::checkBool($var);
        $this->isSimulReleased = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool isSubscribed = 15;</code>
     * @return bool
     */
    public function getIsSubscribed()
    {
        return isset($this->isSubscribed) ? $this->isSubscribed : false;
    }

    public function hasIsSubscribed()
    {
        return isset($this->isSubscribed);
    }

    public function clearIsSubscribed()
    {
        unset($this->isSubscribed);
    }

    /**
     * Generated from protobuf field <code>optional bool isSubscribed = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSubscribed($var)
    {
        GPBUtil::checkBool($var);
        $this->isSubscribed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 rating = 16;</code>
     * @return int
     */
    public function getRating()
    {
        return isset($this->rating) ? $this->rating : 0;
    }

    public function hasRating()
    {
        return isset($this->rating);
    }

    public function clearRating()
    {
        unset($this->rating);
    }

    /**
     * Generated from protobuf field <code>optional int32 rating = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setRating($var)
    {
        GPBUtil::checkInt32($var);
        $this->rating = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool chaptersDescending = 17;</code>
     * @return bool
     */
    public function getChaptersDescending()
    {
        return isset($this->chaptersDescending) ? $this->chaptersDescending : false;
    }

    public function hasChaptersDescending()
    {
        return isset($this->chaptersDescending);
    }

    public function clearChaptersDescending()
    {
        unset($this->chaptersDescending);
    }

    /**
     * Generated from protobuf field <code>optional bool chaptersDescending = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setChaptersDescending($var)
    {
        GPBUtil::checkBool($var);
        $this->chaptersDescending = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 numberOfViews = 18;</code>
     * @return int
     */
    public function getNumberOfViews()
    {
        return isset($this->numberOfViews) ? $this->numberOfViews : 0;
    }

    public function hasNumberOfViews()
    {
        return isset($this->numberOfViews);
    }

    public function clearNumberOfViews()
    {
        unset($this->numberOfViews);
    }

    /**
     * Generated from protobuf field <code>optional uint32 numberOfViews = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setNumberOfViews($var)
    {
        GPBUtil::checkUint32($var);
        $this->numberOfViews = $var;

        return $this;
    }

    /**
     * repeated PublisherItem publisherItems = 19;
     *
     * Generated from protobuf field <code>repeated .MangaPlus.Banner titleBanners = 20;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Banner>
     */
    public function getTitleBanners()
    {
        return $this->titleBanners;
    }

    /**
     * repeated PublisherItem publisherItems = 19;
     *
     * Generated from protobuf field <code>repeated .MangaPlus.Banner titleBanners = 20;</code>
     * @param \App\Api\Protobuf\MangaPlus\Banner[] $var
     * @return $this
     */
    public function setTitleBanners($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Banner::class);
        $this->titleBanners = $arr;

        return $this;
    }

    /**
     * optional UserTickets userTickets = 21;
     *
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter ticketChapterList = 22;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Chapter>
     */
    public function getTicketChapterList()
    {
        return $this->ticketChapterList;
    }

    /**
     * optional UserTickets userTickets = 21;
     *
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter ticketChapterList = 22;</code>
     * @param \App\Api\Protobuf\MangaPlus\Chapter[] $var
     * @return $this
     */
    public function setTicketChapterList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Chapter::class);
        $this->ticketChapterList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title ticketTitleList = 23;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Title>
     */
    public function getTicketTitleList()
    {
        return $this->ticketTitleList;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title ticketTitleList = 23;</code>
     * @param \App\Api\Protobuf\MangaPlus\Title[] $var
     * @return $this
     */
    public function setTicketTitleList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Title::class);
        $this->ticketTitleList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool hasChaptersBetween = 24;</code>
     * @return bool
     */
    public function getHasChaptersBetween()
    {
        return isset($this->hasChaptersBetween) ? $this->hasChaptersBetween : false;
    }

    public function hasHasChaptersBetween()
    {
        return isset($this->hasChaptersBetween);
    }

    public function clearHasChaptersBetween()
    {
        unset($this->hasChaptersBetween);
    }

    /**
     * Generated from protobuf field <code>optional bool hasChaptersBetween = 24;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasChaptersBetween($var)
    {
        GPBUtil::checkBool($var);
        $this->hasChaptersBetween = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Banner publisherBanner = 25;</code>
     * @return \App\Api\Protobuf\MangaPlus\Banner|null
     */
    public function getPublisherBanner()
    {
        return $this->publisherBanner;
    }

    public function hasPublisherBanner()
    {
        return isset($this->publisherBanner);
    }

    public function clearPublisherBanner()
    {
        unset($this->publisherBanner);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Banner publisherBanner = 25;</code>
     * @param \App\Api\Protobuf\MangaPlus\Banner $var
     * @return $this
     */
    public function setPublisherBanner($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Banner::class);
        $this->publisherBanner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetworkList advertisement = 26;</code>
     * @return \App\Api\Protobuf\MangaPlus\AdNetworkList|null
     */
    public function getAdvertisement()
    {
        return $this->advertisement;
    }

    public function hasAdvertisement()
    {
        return isset($this->advertisement);
    }

    public function clearAdvertisement()
    {
        unset($this->advertisement);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.AdNetworkList advertisement = 26;</code>
     * @param \App\Api\Protobuf\MangaPlus\AdNetworkList $var
     * @return $this
     */
    public function setAdvertisement($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\AdNetworkList::class);
        $this->advertisement = $var;

        return $this;
    }

    /**
     * repeated TitleLanguages titleLanguages = 27;
     *
     * Generated from protobuf field <code>repeated .MangaPlus.TitleDetailView.ChapterGroup chapterListGroup = 28;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\TitleDetailView\ChapterGroup>
     */
    public function getChapterListGroup()
    {
        return $this->chapterListGroup;
    }

    /**
     * repeated TitleLanguages titleLanguages = 27;
     *
     * Generated from protobuf field <code>repeated .MangaPlus.TitleDetailView.ChapterGroup chapterListGroup = 28;</code>
     * @param \App\Api\Protobuf\MangaPlus\TitleDetailView\ChapterGroup[] $var
     * @return $this
     */
    public function setChapterListGroup($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\TitleDetailView\ChapterGroup::class);
        $this->chapterListGroup = $arr;

        return $this;
    }

    /**
     * optional FreeViewDialogue freeViewDialogue = 29;
     *
     * Generated from protobuf field <code>optional string regionCode = 30;</code>
     * @return string
     */
    public function getRegionCode()
    {
        return isset($this->regionCode) ? $this->regionCode : '';
    }

    public function hasRegionCode()
    {
        return isset($this->regionCode);
    }

    public function clearRegionCode()
    {
        unset($this->regionCode);
    }

    /**
     * optional FreeViewDialogue freeViewDialogue = 29;
     *
     * Generated from protobuf field <code>optional string regionCode = 30;</code>
     * @param string $var
     * @return $this
     */
    public function setRegionCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->regionCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Tag tags = 31;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Tag>
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Tag tags = 31;</code>
     * @param \App\Api\Protobuf\MangaPlus\Tag[] $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Tag::class);
        $this->tags = $arr;

        return $this;
    }

    /**
     * optional TitleLabels titleLabels = 32;
     * optional Subscription subscription = 33;
     *
     * Generated from protobuf field <code>optional .MangaPlus.Label label = 34;</code>
     * @return \App\Api\Protobuf\MangaPlus\Label|null
     */
    public function getLabel()
    {
        return $this->label;
    }

    public function hasLabel()
    {
        return isset($this->label);
    }

    public function clearLabel()
    {
        unset($this->label);
    }

    /**
     * optional TitleLabels titleLabels = 32;
     * optional Subscription subscription = 33;
     *
     * Generated from protobuf field <code>optional .MangaPlus.Label label = 34;</code>
     * @param \App\Api\Protobuf\MangaPlus\Label $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Label::class);
        $this->label = $var;

        return $this;
    }

    /**
     * optional MetaInfo metaInfo = 36;
     *
     * Generated from protobuf field <code>optional bool isFirstTimeFree = 35;</code>
     * @return bool
     */
    public function getIsFirstTimeFree()
    {
        return isset($this->isFirstTimeFree) ? $this->isFirstTimeFree : false;
    }

    public function hasIsFirstTimeFree()
    {
        return isset($this->isFirstTimeFree);
    }

    public function clearIsFirstTimeFree()
    {
        unset($this->isFirstTimeFree);
    }

    /**
     * optional MetaInfo metaInfo = 36;
     *
     * Generated from protobuf field <code>optional bool isFirstTimeFree = 35;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFirstTimeFree($var)
    {
        GPBUtil::checkBool($var);
        $this->isFirstTimeFree = $var;

        return $this;
    }

}

