<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Title</code>
 */
class Title extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional uint32 titleId = 1;</code>
     */
    protected $titleId = null;
    /**
     * Generated from protobuf field <code>optional string name = 2;</code>
     */
    protected $name = null;
    /**
     * Generated from protobuf field <code>optional string author = 3;</code>
     */
    protected $author = null;
    /**
     * Generated from protobuf field <code>optional string portraitImageUrl = 4;</code>
     */
    protected $portraitImageUrl = null;
    /**
     * Generated from protobuf field <code>optional string landscapeImageUrl = 5;</code>
     */
    protected $landscapeImageUrl = null;
    /**
     * Generated from protobuf field <code>optional uint32 viewCount = 6;</code>
     */
    protected $viewCount = null;
    /**
     * Generated from protobuf field <code>optional int32 language = 7;</code>
     */
    protected $language = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $titleId
     *     @type string $name
     *     @type string $author
     *     @type string $portraitImageUrl
     *     @type string $landscapeImageUrl
     *     @type int $viewCount
     *     @type int $language
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 titleId = 1;</code>
     * @return int
     */
    public function getTitleId()
    {
        return isset($this->titleId) ? $this->titleId : 0;
    }

    public function hasTitleId()
    {
        return isset($this->titleId);
    }

    public function clearTitleId()
    {
        unset($this->titleId);
    }

    /**
     * Generated from protobuf field <code>optional uint32 titleId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTitleId($var)
    {
        GPBUtil::checkUint32($var);
        $this->titleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Generated from protobuf field <code>optional string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string author = 3;</code>
     * @return string
     */
    public function getAuthor()
    {
        return isset($this->author) ? $this->author : '';
    }

    public function hasAuthor()
    {
        return isset($this->author);
    }

    public function clearAuthor()
    {
        unset($this->author);
    }

    /**
     * Generated from protobuf field <code>optional string author = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthor($var)
    {
        GPBUtil::checkString($var, True);
        $this->author = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string portraitImageUrl = 4;</code>
     * @return string
     */
    public function getPortraitImageUrl()
    {
        return isset($this->portraitImageUrl) ? $this->portraitImageUrl : '';
    }

    public function hasPortraitImageUrl()
    {
        return isset($this->portraitImageUrl);
    }

    public function clearPortraitImageUrl()
    {
        unset($this->portraitImageUrl);
    }

    /**
     * Generated from protobuf field <code>optional string portraitImageUrl = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPortraitImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->portraitImageUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string landscapeImageUrl = 5;</code>
     * @return string
     */
    public function getLandscapeImageUrl()
    {
        return isset($this->landscapeImageUrl) ? $this->landscapeImageUrl : '';
    }

    public function hasLandscapeImageUrl()
    {
        return isset($this->landscapeImageUrl);
    }

    public function clearLandscapeImageUrl()
    {
        unset($this->landscapeImageUrl);
    }

    /**
     * Generated from protobuf field <code>optional string landscapeImageUrl = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLandscapeImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->landscapeImageUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 viewCount = 6;</code>
     * @return int
     */
    public function getViewCount()
    {
        return isset($this->viewCount) ? $this->viewCount : 0;
    }

    public function hasViewCount()
    {
        return isset($this->viewCount);
    }

    public function clearViewCount()
    {
        unset($this->viewCount);
    }

    /**
     * Generated from protobuf field <code>optional uint32 viewCount = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setViewCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->viewCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 language = 7;</code>
     * @return int
     */
    public function getLanguage()
    {
        return isset($this->language) ? $this->language : 0;
    }

    public function hasLanguage()
    {
        return isset($this->language);
    }

    public function clearLanguage()
    {
        unset($this->language);
    }

    /**
     * Generated from protobuf field <code>optional int32 language = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkInt32($var);
        $this->language = $var;

        return $this;
    }

}

