<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.Title</code>
 */
class Title extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 titleId = 1;</code>
     */
    protected $titleId = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string author = 3;</code>
     */
    protected $author = '';
    /**
     * Generated from protobuf field <code>string portraitImageUrl = 4;</code>
     */
    protected $portraitImageUrl = '';
    /**
     * Generated from protobuf field <code>string landscapeImageUrl = 5;</code>
     */
    protected $landscapeImageUrl = '';
    /**
     * Generated from protobuf field <code>uint32 viewCount = 6;</code>
     */
    protected $viewCount = 0;
    /**
     * Generated from protobuf field <code>int32 language = 7;</code>
     */
    protected $language = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $titleId
     *     @type string $name
     *     @type string $author
     *     @type string $portraitImageUrl
     *     @type string $landscapeImageUrl
     *     @type int $viewCount
     *     @type int $language
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 titleId = 1;</code>
     * @return int
     */
    public function getTitleId()
    {
        return $this->titleId;
    }

    /**
     * Generated from protobuf field <code>uint32 titleId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTitleId($var)
    {
        GPBUtil::checkUint32($var);
        $this->titleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string author = 3;</code>
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * Generated from protobuf field <code>string author = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthor($var)
    {
        GPBUtil::checkString($var, True);
        $this->author = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string portraitImageUrl = 4;</code>
     * @return string
     */
    public function getPortraitImageUrl()
    {
        return $this->portraitImageUrl;
    }

    /**
     * Generated from protobuf field <code>string portraitImageUrl = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPortraitImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->portraitImageUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string landscapeImageUrl = 5;</code>
     * @return string
     */
    public function getLandscapeImageUrl()
    {
        return $this->landscapeImageUrl;
    }

    /**
     * Generated from protobuf field <code>string landscapeImageUrl = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLandscapeImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->landscapeImageUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 viewCount = 6;</code>
     * @return int
     */
    public function getViewCount()
    {
        return $this->viewCount;
    }

    /**
     * Generated from protobuf field <code>uint32 viewCount = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setViewCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->viewCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 language = 7;</code>
     * @return int
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>int32 language = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkInt32($var);
        $this->language = $var;

        return $this;
    }

}

