<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.TitleContainer</code>
 */
class TitleContainer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string mainName = 1;</code>
     */
    protected $mainName = '';
    /**
     * Utilise Title ou TitleDetail
     *
     * Generated from protobuf field <code>repeated .MangaPlus.Title multiLangTitles = 2;</code>
     */
    private $multiLangTitles;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Category categories = 3;</code>
     */
    private $categories;
    /**
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     */
    protected $timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mainName
     *     @type \App\Api\Protobuf\MangaPlus\Title[] $multiLangTitles
     *           Utilise Title ou TitleDetail
     *     @type \App\Api\Protobuf\MangaPlus\Category[] $categories
     *     @type int|string $timestamp
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string mainName = 1;</code>
     * @return string
     */
    public function getMainName()
    {
        return $this->mainName;
    }

    /**
     * Generated from protobuf field <code>string mainName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMainName($var)
    {
        GPBUtil::checkString($var, True);
        $this->mainName = $var;

        return $this;
    }

    /**
     * Utilise Title ou TitleDetail
     *
     * Generated from protobuf field <code>repeated .MangaPlus.Title multiLangTitles = 2;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Title>
     */
    public function getMultiLangTitles()
    {
        return $this->multiLangTitles;
    }

    /**
     * Utilise Title ou TitleDetail
     *
     * Generated from protobuf field <code>repeated .MangaPlus.Title multiLangTitles = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\Title[] $var
     * @return $this
     */
    public function setMultiLangTitles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Title::class);
        $this->multiLangTitles = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Category categories = 3;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Category>
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Category categories = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\Category[] $var
     * @return $this
     */
    public function setCategories($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Category::class);
        $this->categories = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

}

