<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.TitleDetailView</code>
 */
class TitleDetailView extends \Google\Protobuf\Internal\Message
{
    /**
     * Conservé du v1
     *
     * Generated from protobuf field <code>.MangaPlus.Title title = 1;</code>
     */
    protected $title = null;
    /**
     * Generated from protobuf field <code>string titleImageUrl = 2;</code>
     */
    protected $titleImageUrl = '';
    /**
     * Synopsis
     *
     * Generated from protobuf field <code>string overview = 3;</code>
     */
    protected $overview = '';
    /**
     * Generated from protobuf field <code>string backgroundImageUrl = 4;</code>
     */
    protected $backgroundImageUrl = '';
    /**
     * Generated from protobuf field <code>int64 nextTimeStamp = 5;</code>
     */
    protected $nextTimeStamp = 0;
    /**
     * Generated from protobuf field <code>int32 updateTiming = 6;</code>
     */
    protected $updateTiming = 0;
    /**
     * Generated from protobuf field <code>string viewingPeriodDescription = 7;</code>
     */
    protected $viewingPeriodDescription = '';
    /**
     * Generated from protobuf field <code>string nonAppearanceInfo = 8;</code>
     */
    protected $nonAppearanceInfo = '';
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter firstChapterList = 9;</code>
     */
    private $firstChapterList;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter lastChapterList = 10;</code>
     */
    private $lastChapterList;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner banners = 11;</code>
     */
    private $banners;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title recommendedTitleList = 12;</code>
     */
    private $recommendedTitleList;
    /**
     * SnsShare dans le v2
     *
     * Generated from protobuf field <code>.MangaPlus.Sns sns = 13;</code>
     */
    protected $sns = null;
    /**
     * Generated from protobuf field <code>bool isSimulReleased = 14;</code>
     */
    protected $isSimulReleased = false;
    /**
     * Generated from protobuf field <code>bool isSubscribed = 15;</code>
     */
    protected $isSubscribed = false;
    /**
     * Generated from protobuf field <code>int32 rating = 16;</code>
     */
    protected $rating = 0;
    /**
     * Generated from protobuf field <code>bool chaptersDescending = 17;</code>
     */
    protected $chaptersDescending = false;
    /**
     * Generated from protobuf field <code>uint32 numberOfViews = 18;</code>
     */
    protected $numberOfViews = 0;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner titleBanners = 20;</code>
     */
    private $titleBanners;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter ticketChapterList = 22;</code>
     */
    private $ticketChapterList;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title ticketTitleList = 23;</code>
     */
    private $ticketTitleList;
    /**
     * Generated from protobuf field <code>bool hasChaptersBetween = 24;</code>
     */
    protected $hasChaptersBetween = false;
    /**
     * Generated from protobuf field <code>.MangaPlus.Banner publisherBanner = 25;</code>
     */
    protected $publisherBanner = null;
    /**
     * Generated from protobuf field <code>.MangaPlus.AdNetworkList advertisement = 26;</code>
     */
    protected $advertisement = null;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.LanguageVersion availableLanguages = 27;</code>
     */
    private $availableLanguages;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.ChapterGroup chapterListGroup = 28;</code>
     */
    private $chapterListGroup;
    /**
     * Generated from protobuf field <code>string regionCode = 30;</code>
     */
    protected $regionCode = '';
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Tag tags = 31;</code>
     */
    private $tags;
    /**
     * Generated from protobuf field <code>.MangaPlus.Label label = 34;</code>
     */
    protected $label = null;
    /**
     * Generated from protobuf field <code>bool isFirstTimeFree = 35;</code>
     */
    protected $isFirstTimeFree = false;
    /**
     * Ajouté du v2
     *
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter chapters = 38;</code>
     */
    private $chapters;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Title $title
     *           Conservé du v1
     *     @type string $titleImageUrl
     *     @type string $overview
     *           Synopsis
     *     @type string $backgroundImageUrl
     *     @type int|string $nextTimeStamp
     *     @type int $updateTiming
     *     @type string $viewingPeriodDescription
     *     @type string $nonAppearanceInfo
     *     @type \App\Api\Protobuf\MangaPlus\Chapter[] $firstChapterList
     *     @type \App\Api\Protobuf\MangaPlus\Chapter[] $lastChapterList
     *     @type \App\Api\Protobuf\MangaPlus\Banner[] $banners
     *     @type \App\Api\Protobuf\MangaPlus\Title[] $recommendedTitleList
     *     @type \App\Api\Protobuf\MangaPlus\Sns $sns
     *           SnsShare dans le v2
     *     @type bool $isSimulReleased
     *     @type bool $isSubscribed
     *     @type int $rating
     *     @type bool $chaptersDescending
     *     @type int $numberOfViews
     *     @type \App\Api\Protobuf\MangaPlus\Banner[] $titleBanners
     *     @type \App\Api\Protobuf\MangaPlus\Chapter[] $ticketChapterList
     *     @type \App\Api\Protobuf\MangaPlus\Title[] $ticketTitleList
     *     @type bool $hasChaptersBetween
     *     @type \App\Api\Protobuf\MangaPlus\Banner $publisherBanner
     *     @type \App\Api\Protobuf\MangaPlus\AdNetworkList $advertisement
     *     @type \App\Api\Protobuf\MangaPlus\LanguageVersion[] $availableLanguages
     *     @type \App\Api\Protobuf\MangaPlus\ChapterGroup[] $chapterListGroup
     *     @type string $regionCode
     *     @type \App\Api\Protobuf\MangaPlus\Tag[] $tags
     *     @type \App\Api\Protobuf\MangaPlus\Label $label
     *     @type bool $isFirstTimeFree
     *     @type \App\Api\Protobuf\MangaPlus\Chapter[] $chapters
     *           Ajouté du v2
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Conservé du v1
     *
     * Generated from protobuf field <code>.MangaPlus.Title title = 1;</code>
     * @return \App\Api\Protobuf\MangaPlus\Title|null
     */
    public function getTitle()
    {
        return $this->title;
    }

    public function hasTitle()
    {
        return isset($this->title);
    }

    public function clearTitle()
    {
        unset($this->title);
    }

    /**
     * Conservé du v1
     *
     * Generated from protobuf field <code>.MangaPlus.Title title = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\Title $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Title::class);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string titleImageUrl = 2;</code>
     * @return string
     */
    public function getTitleImageUrl()
    {
        return $this->titleImageUrl;
    }

    /**
     * Generated from protobuf field <code>string titleImageUrl = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitleImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->titleImageUrl = $var;

        return $this;
    }

    /**
     * Synopsis
     *
     * Generated from protobuf field <code>string overview = 3;</code>
     * @return string
     */
    public function getOverview()
    {
        return $this->overview;
    }

    /**
     * Synopsis
     *
     * Generated from protobuf field <code>string overview = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOverview($var)
    {
        GPBUtil::checkString($var, True);
        $this->overview = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string backgroundImageUrl = 4;</code>
     * @return string
     */
    public function getBackgroundImageUrl()
    {
        return $this->backgroundImageUrl;
    }

    /**
     * Generated from protobuf field <code>string backgroundImageUrl = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBackgroundImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->backgroundImageUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 nextTimeStamp = 5;</code>
     * @return int|string
     */
    public function getNextTimeStamp()
    {
        return $this->nextTimeStamp;
    }

    /**
     * Generated from protobuf field <code>int64 nextTimeStamp = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNextTimeStamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->nextTimeStamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 updateTiming = 6;</code>
     * @return int
     */
    public function getUpdateTiming()
    {
        return $this->updateTiming;
    }

    /**
     * Generated from protobuf field <code>int32 updateTiming = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdateTiming($var)
    {
        GPBUtil::checkInt32($var);
        $this->updateTiming = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string viewingPeriodDescription = 7;</code>
     * @return string
     */
    public function getViewingPeriodDescription()
    {
        return $this->viewingPeriodDescription;
    }

    /**
     * Generated from protobuf field <code>string viewingPeriodDescription = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setViewingPeriodDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->viewingPeriodDescription = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nonAppearanceInfo = 8;</code>
     * @return string
     */
    public function getNonAppearanceInfo()
    {
        return $this->nonAppearanceInfo;
    }

    /**
     * Generated from protobuf field <code>string nonAppearanceInfo = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setNonAppearanceInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->nonAppearanceInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter firstChapterList = 9;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Chapter>
     */
    public function getFirstChapterList()
    {
        return $this->firstChapterList;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter firstChapterList = 9;</code>
     * @param \App\Api\Protobuf\MangaPlus\Chapter[] $var
     * @return $this
     */
    public function setFirstChapterList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Chapter::class);
        $this->firstChapterList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter lastChapterList = 10;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Chapter>
     */
    public function getLastChapterList()
    {
        return $this->lastChapterList;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter lastChapterList = 10;</code>
     * @param \App\Api\Protobuf\MangaPlus\Chapter[] $var
     * @return $this
     */
    public function setLastChapterList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Chapter::class);
        $this->lastChapterList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner banners = 11;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Banner>
     */
    public function getBanners()
    {
        return $this->banners;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner banners = 11;</code>
     * @param \App\Api\Protobuf\MangaPlus\Banner[] $var
     * @return $this
     */
    public function setBanners($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Banner::class);
        $this->banners = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title recommendedTitleList = 12;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Title>
     */
    public function getRecommendedTitleList()
    {
        return $this->recommendedTitleList;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title recommendedTitleList = 12;</code>
     * @param \App\Api\Protobuf\MangaPlus\Title[] $var
     * @return $this
     */
    public function setRecommendedTitleList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Title::class);
        $this->recommendedTitleList = $arr;

        return $this;
    }

    /**
     * SnsShare dans le v2
     *
     * Generated from protobuf field <code>.MangaPlus.Sns sns = 13;</code>
     * @return \App\Api\Protobuf\MangaPlus\Sns|null
     */
    public function getSns()
    {
        return $this->sns;
    }

    public function hasSns()
    {
        return isset($this->sns);
    }

    public function clearSns()
    {
        unset($this->sns);
    }

    /**
     * SnsShare dans le v2
     *
     * Generated from protobuf field <code>.MangaPlus.Sns sns = 13;</code>
     * @param \App\Api\Protobuf\MangaPlus\Sns $var
     * @return $this
     */
    public function setSns($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Sns::class);
        $this->sns = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isSimulReleased = 14;</code>
     * @return bool
     */
    public function getIsSimulReleased()
    {
        return $this->isSimulReleased;
    }

    /**
     * Generated from protobuf field <code>bool isSimulReleased = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSimulReleased($var)
    {
        GPBUtil::checkBool($var);
        $this->isSimulReleased = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isSubscribed = 15;</code>
     * @return bool
     */
    public function getIsSubscribed()
    {
        return $this->isSubscribed;
    }

    /**
     * Generated from protobuf field <code>bool isSubscribed = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSubscribed($var)
    {
        GPBUtil::checkBool($var);
        $this->isSubscribed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rating = 16;</code>
     * @return int
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * Generated from protobuf field <code>int32 rating = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setRating($var)
    {
        GPBUtil::checkInt32($var);
        $this->rating = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool chaptersDescending = 17;</code>
     * @return bool
     */
    public function getChaptersDescending()
    {
        return $this->chaptersDescending;
    }

    /**
     * Generated from protobuf field <code>bool chaptersDescending = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setChaptersDescending($var)
    {
        GPBUtil::checkBool($var);
        $this->chaptersDescending = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 numberOfViews = 18;</code>
     * @return int
     */
    public function getNumberOfViews()
    {
        return $this->numberOfViews;
    }

    /**
     * Generated from protobuf field <code>uint32 numberOfViews = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setNumberOfViews($var)
    {
        GPBUtil::checkUint32($var);
        $this->numberOfViews = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner titleBanners = 20;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Banner>
     */
    public function getTitleBanners()
    {
        return $this->titleBanners;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner titleBanners = 20;</code>
     * @param \App\Api\Protobuf\MangaPlus\Banner[] $var
     * @return $this
     */
    public function setTitleBanners($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Banner::class);
        $this->titleBanners = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter ticketChapterList = 22;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Chapter>
     */
    public function getTicketChapterList()
    {
        return $this->ticketChapterList;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter ticketChapterList = 22;</code>
     * @param \App\Api\Protobuf\MangaPlus\Chapter[] $var
     * @return $this
     */
    public function setTicketChapterList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Chapter::class);
        $this->ticketChapterList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title ticketTitleList = 23;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Title>
     */
    public function getTicketTitleList()
    {
        return $this->ticketTitleList;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title ticketTitleList = 23;</code>
     * @param \App\Api\Protobuf\MangaPlus\Title[] $var
     * @return $this
     */
    public function setTicketTitleList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Title::class);
        $this->ticketTitleList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool hasChaptersBetween = 24;</code>
     * @return bool
     */
    public function getHasChaptersBetween()
    {
        return $this->hasChaptersBetween;
    }

    /**
     * Generated from protobuf field <code>bool hasChaptersBetween = 24;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasChaptersBetween($var)
    {
        GPBUtil::checkBool($var);
        $this->hasChaptersBetween = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Banner publisherBanner = 25;</code>
     * @return \App\Api\Protobuf\MangaPlus\Banner|null
     */
    public function getPublisherBanner()
    {
        return $this->publisherBanner;
    }

    public function hasPublisherBanner()
    {
        return isset($this->publisherBanner);
    }

    public function clearPublisherBanner()
    {
        unset($this->publisherBanner);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Banner publisherBanner = 25;</code>
     * @param \App\Api\Protobuf\MangaPlus\Banner $var
     * @return $this
     */
    public function setPublisherBanner($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Banner::class);
        $this->publisherBanner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.AdNetworkList advertisement = 26;</code>
     * @return \App\Api\Protobuf\MangaPlus\AdNetworkList|null
     */
    public function getAdvertisement()
    {
        return $this->advertisement;
    }

    public function hasAdvertisement()
    {
        return isset($this->advertisement);
    }

    public function clearAdvertisement()
    {
        unset($this->advertisement);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.AdNetworkList advertisement = 26;</code>
     * @param \App\Api\Protobuf\MangaPlus\AdNetworkList $var
     * @return $this
     */
    public function setAdvertisement($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\AdNetworkList::class);
        $this->advertisement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.LanguageVersion availableLanguages = 27;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\LanguageVersion>
     */
    public function getAvailableLanguages()
    {
        return $this->availableLanguages;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.LanguageVersion availableLanguages = 27;</code>
     * @param \App\Api\Protobuf\MangaPlus\LanguageVersion[] $var
     * @return $this
     */
    public function setAvailableLanguages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\LanguageVersion::class);
        $this->availableLanguages = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.ChapterGroup chapterListGroup = 28;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\ChapterGroup>
     */
    public function getChapterListGroup()
    {
        return $this->chapterListGroup;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.ChapterGroup chapterListGroup = 28;</code>
     * @param \App\Api\Protobuf\MangaPlus\ChapterGroup[] $var
     * @return $this
     */
    public function setChapterListGroup($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\ChapterGroup::class);
        $this->chapterListGroup = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string regionCode = 30;</code>
     * @return string
     */
    public function getRegionCode()
    {
        return $this->regionCode;
    }

    /**
     * Generated from protobuf field <code>string regionCode = 30;</code>
     * @param string $var
     * @return $this
     */
    public function setRegionCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->regionCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Tag tags = 31;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Tag>
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Tag tags = 31;</code>
     * @param \App\Api\Protobuf\MangaPlus\Tag[] $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Tag::class);
        $this->tags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Label label = 34;</code>
     * @return \App\Api\Protobuf\MangaPlus\Label|null
     */
    public function getLabel()
    {
        return $this->label;
    }

    public function hasLabel()
    {
        return isset($this->label);
    }

    public function clearLabel()
    {
        unset($this->label);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Label label = 34;</code>
     * @param \App\Api\Protobuf\MangaPlus\Label $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Label::class);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isFirstTimeFree = 35;</code>
     * @return bool
     */
    public function getIsFirstTimeFree()
    {
        return $this->isFirstTimeFree;
    }

    /**
     * Generated from protobuf field <code>bool isFirstTimeFree = 35;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFirstTimeFree($var)
    {
        GPBUtil::checkBool($var);
        $this->isFirstTimeFree = $var;

        return $this;
    }

    /**
     * Ajouté du v2
     *
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter chapters = 38;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Chapter>
     */
    public function getChapters()
    {
        return $this->chapters;
    }

    /**
     * Ajouté du v2
     *
     * Generated from protobuf field <code>repeated .MangaPlus.Chapter chapters = 38;</code>
     * @param \App\Api\Protobuf\MangaPlus\Chapter[] $var
     * @return $this
     */
    public function setChapters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Chapter::class);
        $this->chapters = $arr;

        return $this;
    }

}

