<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.TitleList</code>
 */
class TitleList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string listName = 1;</code>
     */
    protected $listName = null;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title featuredTitles = 2;</code>
     */
    private $featuredTitles;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $listName
     *     @type \App\Api\Protobuf\MangaPlus\Title[] $featuredTitles
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string listName = 1;</code>
     * @return string
     */
    public function getListName()
    {
        return isset($this->listName) ? $this->listName : '';
    }

    public function hasListName()
    {
        return isset($this->listName);
    }

    public function clearListName()
    {
        unset($this->listName);
    }

    /**
     * Generated from protobuf field <code>optional string listName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setListName($var)
    {
        GPBUtil::checkString($var, True);
        $this->listName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title featuredTitles = 2;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Title>
     */
    public function getFeaturedTitles()
    {
        return $this->featuredTitles;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title featuredTitles = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\Title[] $var
     * @return $this
     */
    public function setFeaturedTitles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Title::class);
        $this->featuredTitles = $arr;

        return $this;
    }

}

