<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.UpdatedTitle</code>
 */
class UpdatedTitle extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .MangaPlus.Title title = 1;</code>
     */
    protected $title = null;
    /**
     * Generated from protobuf field <code>optional uint32 chapterId = 2;</code>
     */
    protected $chapterId = null;
    /**
     * Generated from protobuf field <code>optional string chapterName = 3;</code>
     */
    protected $chapterName = null;
    /**
     * Generated from protobuf field <code>optional string chapterSubTitle = 4;</code>
     */
    protected $chapterSubTitle = null;
    /**
     * Generated from protobuf field <code>optional bool isLatest = 5;</code>
     */
    protected $isLatest = null;
    /**
     * Generated from protobuf field <code>optional bool isVerticalOnly = 6;</code>
     */
    protected $isVerticalOnly = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Title $title
     *     @type int $chapterId
     *     @type string $chapterName
     *     @type string $chapterSubTitle
     *     @type bool $isLatest
     *     @type bool $isVerticalOnly
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Title title = 1;</code>
     * @return \App\Api\Protobuf\MangaPlus\Title|null
     */
    public function getTitle()
    {
        return $this->title;
    }

    public function hasTitle()
    {
        return isset($this->title);
    }

    public function clearTitle()
    {
        unset($this->title);
    }

    /**
     * Generated from protobuf field <code>optional .MangaPlus.Title title = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\Title $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Title::class);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 chapterId = 2;</code>
     * @return int
     */
    public function getChapterId()
    {
        return isset($this->chapterId) ? $this->chapterId : 0;
    }

    public function hasChapterId()
    {
        return isset($this->chapterId);
    }

    public function clearChapterId()
    {
        unset($this->chapterId);
    }

    /**
     * Generated from protobuf field <code>optional uint32 chapterId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setChapterId($var)
    {
        GPBUtil::checkUint32($var);
        $this->chapterId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string chapterName = 3;</code>
     * @return string
     */
    public function getChapterName()
    {
        return isset($this->chapterName) ? $this->chapterName : '';
    }

    public function hasChapterName()
    {
        return isset($this->chapterName);
    }

    public function clearChapterName()
    {
        unset($this->chapterName);
    }

    /**
     * Generated from protobuf field <code>optional string chapterName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setChapterName($var)
    {
        GPBUtil::checkString($var, True);
        $this->chapterName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string chapterSubTitle = 4;</code>
     * @return string
     */
    public function getChapterSubTitle()
    {
        return isset($this->chapterSubTitle) ? $this->chapterSubTitle : '';
    }

    public function hasChapterSubTitle()
    {
        return isset($this->chapterSubTitle);
    }

    public function clearChapterSubTitle()
    {
        unset($this->chapterSubTitle);
    }

    /**
     * Generated from protobuf field <code>optional string chapterSubTitle = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setChapterSubTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->chapterSubTitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool isLatest = 5;</code>
     * @return bool
     */
    public function getIsLatest()
    {
        return isset($this->isLatest) ? $this->isLatest : false;
    }

    public function hasIsLatest()
    {
        return isset($this->isLatest);
    }

    public function clearIsLatest()
    {
        unset($this->isLatest);
    }

    /**
     * Generated from protobuf field <code>optional bool isLatest = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLatest($var)
    {
        GPBUtil::checkBool($var);
        $this->isLatest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool isVerticalOnly = 6;</code>
     * @return bool
     */
    public function getIsVerticalOnly()
    {
        return isset($this->isVerticalOnly) ? $this->isVerticalOnly : false;
    }

    public function hasIsVerticalOnly()
    {
        return isset($this->isVerticalOnly);
    }

    public function clearIsVerticalOnly()
    {
        unset($this->isVerticalOnly);
    }

    /**
     * Generated from protobuf field <code>optional bool isVerticalOnly = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsVerticalOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->isVerticalOnly = $var;

        return $this;
    }

}

