<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.UpdatedTitleGroup</code>
 */
class UpdatedTitleGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string groupName = 1;</code>
     */
    protected $groupName = null;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.UpdatedTitle titles = 2;</code>
     */
    private $titles;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $groupName
     *     @type \App\Api\Protobuf\MangaPlus\UpdatedTitle[] $titles
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string groupName = 1;</code>
     * @return string
     */
    public function getGroupName()
    {
        return isset($this->groupName) ? $this->groupName : '';
    }

    public function hasGroupName()
    {
        return isset($this->groupName);
    }

    public function clearGroupName()
    {
        unset($this->groupName);
    }

    /**
     * Generated from protobuf field <code>optional string groupName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupName($var)
    {
        GPBUtil::checkString($var, True);
        $this->groupName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.UpdatedTitle titles = 2;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\UpdatedTitle>
     */
    public function getTitles()
    {
        return $this->titles;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.UpdatedTitle titles = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\UpdatedTitle[] $var
     * @return $this
     */
    public function setTitles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\UpdatedTitle::class);
        $this->titles = $arr;

        return $this;
    }

}

