<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.UpdatedTitle</code>
 */
class UpdatedTitle extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.MangaPlus.Title title = 1;</code>
     */
    protected $title = null;
    /**
     * Generated from protobuf field <code>uint32 chapterId = 2;</code>
     */
    protected $chapterId = 0;
    /**
     * Generated from protobuf field <code>string chapterName = 3;</code>
     */
    protected $chapterName = '';
    /**
     * Generated from protobuf field <code>string chapterSubTitle = 4;</code>
     */
    protected $chapterSubTitle = '';
    /**
     * Generated from protobuf field <code>bool isLatest = 5;</code>
     */
    protected $isLatest = false;
    /**
     * Generated from protobuf field <code>bool isVerticalOnly = 6;</code>
     */
    protected $isVerticalOnly = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Title $title
     *     @type int $chapterId
     *     @type string $chapterName
     *     @type string $chapterSubTitle
     *     @type bool $isLatest
     *     @type bool $isVerticalOnly
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Title title = 1;</code>
     * @return \App\Api\Protobuf\MangaPlus\Title|null
     */
    public function getTitle()
    {
        return $this->title;
    }

    public function hasTitle()
    {
        return isset($this->title);
    }

    public function clearTitle()
    {
        unset($this->title);
    }

    /**
     * Generated from protobuf field <code>.MangaPlus.Title title = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\Title $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkMessage($var, \App\Api\Protobuf\MangaPlus\Title::class);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 chapterId = 2;</code>
     * @return int
     */
    public function getChapterId()
    {
        return $this->chapterId;
    }

    /**
     * Generated from protobuf field <code>uint32 chapterId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setChapterId($var)
    {
        GPBUtil::checkUint32($var);
        $this->chapterId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string chapterName = 3;</code>
     * @return string
     */
    public function getChapterName()
    {
        return $this->chapterName;
    }

    /**
     * Generated from protobuf field <code>string chapterName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setChapterName($var)
    {
        GPBUtil::checkString($var, True);
        $this->chapterName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string chapterSubTitle = 4;</code>
     * @return string
     */
    public function getChapterSubTitle()
    {
        return $this->chapterSubTitle;
    }

    /**
     * Generated from protobuf field <code>string chapterSubTitle = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setChapterSubTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->chapterSubTitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isLatest = 5;</code>
     * @return bool
     */
    public function getIsLatest()
    {
        return $this->isLatest;
    }

    /**
     * Generated from protobuf field <code>bool isLatest = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLatest($var)
    {
        GPBUtil::checkBool($var);
        $this->isLatest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isVerticalOnly = 6;</code>
     * @return bool
     */
    public function getIsVerticalOnly()
    {
        return $this->isVerticalOnly;
    }

    /**
     * Generated from protobuf field <code>bool isVerticalOnly = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsVerticalOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->isVerticalOnly = $var;

        return $this;
    }

}

