<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShueishaMangaPlus.proto

namespace App\Api\Protobuf\MangaPlus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>MangaPlus.WebHomeView</code>
 */
class WebHomeView extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner topBanners = 1;</code>
     */
    private $topBanners;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.UpdatedTitleGroup groups = 2;</code>
     */
    private $groups;
    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title ranking = 3;</code>
     */
    private $ranking;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Api\Protobuf\MangaPlus\Banner[] $topBanners
     *     @type \App\Api\Protobuf\MangaPlus\UpdatedTitleGroup[] $groups
     *     @type \App\Api\Protobuf\MangaPlus\Title[] $ranking
     * }
     */
    public function __construct($data = NULL) {
        \App\Api\Protobuf\GPBMetadata\ShueishaMangaPlus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner topBanners = 1;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Banner>
     */
    public function getTopBanners()
    {
        return $this->topBanners;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Banner topBanners = 1;</code>
     * @param \App\Api\Protobuf\MangaPlus\Banner[] $var
     * @return $this
     */
    public function setTopBanners($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Banner::class);
        $this->topBanners = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.UpdatedTitleGroup groups = 2;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\UpdatedTitleGroup>
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.UpdatedTitleGroup groups = 2;</code>
     * @param \App\Api\Protobuf\MangaPlus\UpdatedTitleGroup[] $var
     * @return $this
     */
    public function setGroups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\UpdatedTitleGroup::class);
        $this->groups = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title ranking = 3;</code>
     * @return RepeatedField<\App\Api\Protobuf\MangaPlus\Title>
     */
    public function getRanking()
    {
        return $this->ranking;
    }

    /**
     * Generated from protobuf field <code>repeated .MangaPlus.Title ranking = 3;</code>
     * @param \App\Api\Protobuf\MangaPlus\Title[] $var
     * @return $this
     */
    public function setRanking($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Api\Protobuf\MangaPlus\Title::class);
        $this->ranking = $arr;

        return $this;
    }

}

